### ISSUE TITLE
Script name shows in Chinese when I set the language to en-US.

### ISSUE THREAD

**Issue by sayo-melu** [violentmonkey/violentmonkey#1265] opened 2021-04-29 02:00 UTC
<img width="888" alt="Screen Shot 2021-04-29 at 09 59 50" src="https://user-images.githubusercontent.com/16492117/116493611-a7b1a300-a8d1-11eb-804f-fb04f23d571f.png">

When browser language is set to.

1. English (Canada)
2. English
3. Chinese (Simplified)
4. Chinese

It shows all in English only when I remove Chinese from my browser.

### Environment
- Browser: Chrome
- Browser version: 90
- Violentmonkey version: v2.12.14
- OS: macOS 11.3

**Comment by gera2ld** [comment] 2021-04-29 02:54
I guess your scripts do not have `@name:en` or `@name:en-CA` defined, but have `@name:zh` or `@name:zh-CN` in them, so the Chinese names are always matched.
It falls back to the default `@name` only when no locale-specific names are matched, which may be English in your case.

This is the expected behavior for now but maybe we can improve it in some way...

**Comment by sayomelu** [comment] 2021-04-29 03:04
[tampermonkey](https://www.ecosia.org/search?q=tampermonkey) shows english correctly. For most script, they use english as their `@name` for default. Treating `@name` as `@name:en` maybe a methord.

**Comment by tophf** [comment] 2021-04-29 03:42
The fact that Violentmonkey chooses a Chinese `@name:zh` when the UI language is English is wrong because the UI language is a strong indication of user's desire and expectation to see the UI and all the stuff in the chosen language. Even if the script doesn't have an explicit `@name:en` Violentmonkey should not use a non-default language because it makes the UI non-uniform, which is harder to read.

**Comment by gera2ld** [comment] 2021-04-29 03:57
> The fact that Violentmonkey chooses a Chinese `@name:zh` when the UI language is English is wrong because the UI language is a strong indication of user's desire and expectation to see the UI and all the stuff in the chosen language.

I totally agree with this.

I think you are assuming that default language is always English. This may be a good idea to solve this problem though.

**Comment by tophf** [comment] 2021-04-29 04:01
>I think you are assuming that default language is always English.

My point was slightly different: Violentmonkey should not choose a nonprimary language regardless of the actual language of `@name`.

**Comment by gera2ld** [comment] 2021-04-29 04:14
What if the primary language is not available but a preferred language is? For example:

preferred locales: `['jp', 'zh']` - without English
names: `@name:zh`, `@name`

**Comment by tophf** [comment] 2021-04-29 04:29
And what is the UI language in your example?

**Comment by gera2ld** [comment] 2021-04-29 04:57
ui language should always be the first one in locale list IIRC



Sent from my Mi phone
Apr 29, 2021 12:30 wrote on tophf ***@***.***>:

And what is the UI language in your example?

**Comment by tophf** [comment] 2021-04-29 05:02
So it's `jp`, in which case showing a Chinese name would be **definitely** inconsistent with the UI language, whereas showing `@name` **might be** correct as it could be in Japanese but even if not, it's the author's responsibility so the users can pester the author, not us. In other words, my point is that Violentmonkey shouldn't choose a definite miss when there's a possible hit.

**Comment by tophf** [comment] 2021-04-29 05:18
On the other hand Violentmonkey currently behaves just like the browser itself. I hate this behavior which is why I removed the additional languages from the browser settings so that only the primary language is always chosen both by the browser and by Violentmonkey.

As for a solution, I don't think we should use Tampernokey's approach of treating `@name` as `@name:en` as it'll be wrong for non-English cases. We can either a) do nothing as this problem is rare and is a mistake of the userscript's author anyway or b) add a checkbox in advanced options like "Use non-default UI language to display scripts".

**Comment by gera2ld** [comment] 2021-04-29 06:07
We have discussed this before. The "Allow non-default UI language when displaying scripts" option will lead to many mismatch cases for users that accept multiple (maybe similar) locales. I think this is unacceptable to at least Chinese users.

Treating `@name` as `@name:en` might be acceptable if most authors write scripts this way. I don't have any evidence yet.

Or we could add an option to let the user decide what the default language is supposed to be. In other words, `@name` will be regarded as `@name:user-defined-default-lang` if it is not defined explicitly. It's actually a way to change the priority of `@name` to the priority of `user-defined-default-lang` among the locale list.

**Comment by tophf** [comment] 2021-04-29 06:26
> The "Allow non-default UI language when displaying scripts" option will lead to many mismatch cases for users that accept multiple (maybe similar) locales. I think this is unacceptable to at least Chinese users.

This option would be enabled by default so Violentmonkey's behavior won't change.

> Or we could add an option to let the user decide what the default language is supposed to be.

But the user has already expressed their preference by choosing the browser's UI language...

**Comment by tophf** [comment] 2021-06-12 05:41
Closing because the script has an objective mistake by not specifying `@name:en` and assuming that the user's language is English by default. This is not a common mistake either so we shouldn't encourage it by hiding its negative effects. Harass the authors of those scripts or add a custom name explicitly in the second tab of Violentmonkey editor for the script.

**Closed by tophf** 2021-06-12 05:41 UTC
Labels: discussion, works as intended

**Comment by kkocdko** [comment] 2021-08-03 04:12
https://github.com/violentmonkey/violentmonkey/issues/1236#issue-839326631

As my thinking, the GM script standard(if exist) has problem here: script manager couldn't detect `@name` language.

The best behaviour should be: `@name` **always** has language attritube, and the first `@name:xxx` entry be marked as default name for script service website(greasyfork, and others). But now if I add language to the origin `@name` entry, Violentmonkey alert `invaild script`, because no `@name` in script.

Any ideas?

**Comment by tophf** [comment] 2021-08-03 04:43
The `@name` along with `@namespace` serves as an identifier of the script so it can't be omitted.
