### ISSUE TITLE
Unable to install scripts from https://greasyfork.org using incognito mode with Chrome.

### ISSUE THREAD

**Issue by arau0** [violentmonkey/violentmonkey#961] opened 2020-04-12 11:20 UTC
### What is the problem?
Unable to install scripts from https://greasyfork.org using incognito mode with Chrome.

### How to reproduce it?
1. I am not able to install scripts from https://greasyfork.org, when I am using Chrome in incognito mode.  If I am using regular, not incognito mode everything is fine.
2. Example https://greasyfork.org/en/scripts/369400-local-youtube-downloader
3. Click on "Install this script".

### What is the expected result?
To install scripts from https://greasyfork.org using incognito mode with Chrome

### What is the actual result?
Unable to install scripts from https://greasyfork.org using incognito mode with Chrome.

### Environment
- Browser: Chrome
- Browser version: Chrome 80
- Violentmonkey version: 2.12.8 rc3
- OS:Windows

**Comment by tophf** [comment] 2020-04-12 11:24
This is the expected behavior as we shouldn't modify the main profile's database from incognito windows at all. We could add an error message about that though... Thoughts, @gera2ld?

**Comment by arau0** [comment] 2020-04-12 11:32
@tophf I think that's a bug.
When you click on "Install this script", ViolentMonkey should have the same behavior like you're in incognito mode but using the dashboard there is "plus" icon. Once you pressed the "plus" icon we should have ViolentMonkey open in regular mode and the user just have to confirm the installation.

**Comment by tophf** [comment] 2020-04-12 11:33
No, I don't think so. My point was that we should guard the main profile and explicitly warn when an installation attempt was made.

**Comment by arau0** [comment] 2020-04-12 11:39
@tophf :) please, could you explain why then we have in the violentmonkey dashboard open in incognito mode "plus" icon. What will be the point?
I get your point but I can't agreed with that in my scenario.
Once you're in incognito mode and click on "Install this script", we should have the same script open with ViolentMonkey but in regular mode.

**Comment by tophf** [comment] 2020-04-12 11:45
The dashboard always opens in the normal mode and it even creates a new window if there was no normal mode window previously open. So this switching makes it pretty obvious that this is not an incognito window. On the other hand, we could disable the plus button in the popup shown on incognito tabs with a tooltip that installation is not available in incognito.

As for installing while browsing greasyfork or any other site in incognito mode, I'm against it as it violates the basic expectations about incognito mode that it doesn't affect the main profile.

**Comment by tophf** [comment] 2020-04-12 11:51
That said, an alternative solution might be to show a prominent **RED** warning in the installer that it'll install into the main profile...

**Comment by arau0** [comment] 2020-04-12 12:05
@tophf I think you don't get my point.
"Once you're in incognito mode and click on "Install this script", we should have the same script open with ViolentMonkey but in regular mode."
That dosn't mean you're making any chances in incognito mode. 
That mean if you're in incognito mode and press on "install this script", that should called the ViolentMonkey to open but in normal mode. 
If you confirm the installation the changes are made not in incognito, because you're already in normal mode.

**Comment by tophf** [comment] 2020-04-12 12:11
Just because I disagree doesn't mean I don't understand. I do. My concern is that your expectation violates the basic expectation that anything you do within an *incognito web page* can't have an effect on the main profile. 

To sum it up, my suggestions are:
* a warning that this is unsupported
* a confirmation before installing that the user wants to install the script in their main profile
* show the installation tab but with a big red warning inside

**Comment by arau0** [comment] 2020-04-12 12:18
I like to see the beauty in the different opinions, because sometimes that's the only way to improve something :)
What make sense is what the rest of peoples are thinking about that and what will be the result afterwards.

**Comment by arau0** [comment] 2020-04-12 12:47
If you're in incognito mode, visit https://greasyfork.org and click on "Install this script", ViolentMonkey should open the script in regular-normal tab, not in incognito. 
There shouldn't be any warnings, because you're in regular-normal tab, not incognito and the user just have to confirm the installation. Currently we have the options "save", "save and close" and "close", which are perfectly fine.
If the user pressed "save and close" or "close", this regular tab should closed and the user returned to the already open page, which is in incognito mode.

**Comment by tophf** [comment] 2020-04-12 12:50
No need to repeat: your point was clear from the get go. It looks like you miss or intentionally my point though so let's wait for @gera2ld.

**Comment by gera2ld** [comment] 2020-04-13 04:52
I think it's better to allow installation from an incognito window because otherwise it's hard to use.

In my opinion, an extension is something beyonds the normal and incognito modes, more like a background service that provides some common UI, so there is no need to distinguish them.

Some people care a lot about privacy and may expect changes from incognito mode being ignored, we can prevent them from further actions by adding an explicit notice before the first action performs, or just pin a warning at the top like the following image. I guess it could also be added to the privacy policy.

<img width="333" alt="Screen Shot 2020-04-13 at 12 22 08" src="https://user-images.githubusercontent.com/3139113/79091835-6d866980-7d81-11ea-8bff-60fc13728ee7.png">

BTW, AdBlock Plus also applies actions in incognito mode to the normal mode, in other words they don't handle incognito mode differently.

@tophf Do you agree on this?

**Comment by tophf** [comment] 2020-04-13 04:55
Yes, with the warning in the popup looks cool. The same will be shown in the installation page when it's opened from a click inside an incognito tab, I guess.

**Comment by tophf** [comment] 2020-04-13 05:03
On the other hand, maybe the red background should be used only in the installation page, and a standard background in the popup...

**Comment by tophf** [comment] 2020-04-13 05:14
So to clarify, there was indeed a bug (openerTabId cannot be used across different windows) and a UI enhancement to make sure the users don't shoot themselves in the foot.

**Comment by arau0** [comment] 2020-04-13 09:05
@tophf Finally :) Thank you for the bug confirmation.

@gera2ld I agree with you to "allow installation from an incognito window because otherwise it's hard to use".

I already said "If you're in incognito mode, visit https://greasyfork.org and click on "Install this script", ViolentMonkey should open the script in regular-normal tab, not in incognito".

The user is giving appropriate permissions ViolentMonkey to run in incognito tabs. 
If the user don't want any changes to be made by ViolentMonkey will not give this permisions.
That's why I still don't see a point to pin a warning at the top of the dashboard in incognito tab.

BTW, @gera2ld I am not sure if @gorhill is considiring that in future but I don't see such as behavior in uBlockOrigin.

In the end of the day that's my opninion and I see how are considiring it. Respect to your effort and time.

**Comment by gera2ld** [comment] 2020-04-13 09:55
@arau0 Allowing it to run in incognito tabs does not mean to expect the changes to persist.

People might expect to have a brand new profile for Violentmonkey in incognito mode, maybe for experimental purpose, or to use some NSFW userscripts and expect them to vanish after closing the window.

Anyway we don't expect that so we try to avoid confusing users in such a way.

**Comment by tophf** [comment] 2020-04-13 09:56
The warning will be displayed at the bottom in the incognito popup, see #963.

**Closed** 2020-04-13 10:20 UTC
Labels: bug, enhancement

**Comment by arau0** [comment] 2020-04-13 11:06
@gera2ld I see your point and understand it.
