### ISSUE TITLE
Where are the userscripts stored?

### ISSUE THREAD

**Issue by idgas01** [violentmonkey/violentmonkey#1153] opened 2020-12-26 20:35 UTC
In my Firefox Portable profile folder, I have a bunch of subfolders like browser-extension-data, chrome, extensions, etc.  It would take too long to list them all.  Where are my userscripts stored?  It's a portable version of Mozilla Firefox so I don't think that my userscripts are being stored in AppData or some other local computer folder.  Firefox Portable is installed on my USB drive, so I think all my files are on there.

Also, is there a way to put all my userscripts in a different folder like "G:\Userscripts" and have Violentmonkey load them but never delete them?  Like let's say that I forget to export my data as a .zip and I uninstall Violentmonkey.  If my userscripts are in a different non-default folder, will they still stay there or will they be deleted?

**Comment by tophf** [comment] 2020-12-26 20:38
Duplicate of https://github.com/violentmonkey/violentmonkey/discussions/1151

**Closed** 2020-12-26 20:38 UTC
