### ISSUE TITLE
History permission

### ISSUE THREAD

**Issue by john-cj** [violentmonkey/violentmonkey#752] opened 2019-12-08 11:38 UTC
It seems that Violentmonkey doesn't have `"history"` permission. An excerpt from its manifest.json:

``` json
"permissions": [
  "tabs",
  "\u003Call_urls>",
  "webRequest",
  "webRequestBlocking",
  "notifications",
  "storage",
  "unlimitedStorage",
  "clipboardWrite"
],
```

The history permission could be useful. For example, here is my userscript:

``` js
// ==UserScript==
// @grant   none
// @match   https://*.wikipedia.org/*
// @name    Wikipedia
// ==/UserScript==

(function() {
    'use strict';

    function actionFunction() {
        var links = document.querySelectorAll('a');
        var i;
        for (i = 0; i < links.length; i++) {
            var input = document.createElement('input');
            input.type = 'checkbox';
            input.dataset.url = links[i].href;
            input.addEventListener('change', function() {
                let desired_url = this.dataset.url;
                let current_url = window.location.href;
                if (this.checked) {
                    history.replaceState({}, '', desired_url);
                    history.replaceState({}, '', current_url);
                } else {
                    // ???
                }
            });
            links[i].parentElement.insertBefore(input, links[i].nextSibling);
        }
    }

    actionFunction();
})();
```

It adds checkbox after each link on Wikipedia. When you click the checkbox, the link becomes visited.

The problem is that there is no way to make it work backward: i.e. to make link unvisited when you clear the corresponding checkbox.

It could be solved (as far as I understand) with browser API:

``` js
                // not tested
                if (this.checked) {
                    chrome.history.addUrl({url: desired_url});
                } else {
                    chrome.history.deleteUrl({url: desired_url});
                }
```

but since there is no `"history"` permission, it is not possible.

### Environment
- Browser: Chrome
- Browser version:  78.0.3904.108 (Official Build) (32-bit)
- Violentmonkey version: 2.12.2
- OS: Windows 7

**Comment by tophf** [comment] 2019-12-08 11:49
Adding a userscript API ideally should be coordinated with the other managers, primarily Tampermonkey and Greasemonkey. Try proposing the feature in their repos too.

Personally, I'm reluctant to implement this and not just because it's a rare feature, but primarily because this permission has a [warning](https://developer.chrome.com/extensions/permission_warnings) so if Violentmonkey adds it to manifest.json, the extension will be automatically disabled on update for every user until they confirm the new permission and many users won't agree because it doesn't make sense for Violentmonkey to use the history permission. There's a workaround: [optional permissions](https://developer.chrome.com/extensions/permissions) but it's not exactly trivial since we would need to show a confirmation tab for the user on first access to this API. Not exactly impossible but certainly the gain is not worth the effort IMO.

So I'd say this task is something that should be implemented as a separate extension.

**Comment by john-cj** [comment] 2019-12-08 12:01
@tophf Yes, I tend to agree with you.

**Comment by gera2ld** [comment] 2019-12-10 02:00
Totally agree with @tophf .

IMO, no APIs other than those provided by the script manager, i.e. GM_*, are supposed to be used in userscripts, so that they can be easily migrated between different script managers, browsers and platforms.
If you'd like to use the low level APIs directly, you'd better implement another web extension.

Closing as won't fix.

**Closed by gera2ld** 2019-12-10 02:00 UTC
Labels: discussion

**Comment by spodermenpls** [comment] 2020-06-12 02:12
I am not sure if someone already contacted you with this proposal, but this issue was the closest thing to it I was able to find:

The GoodTwitter2 userscript, increasingly popular due to Twitter disabling any workaround to revert to the now defunct Classic layout, needs access to the `window.history` API, which only Tampermonkey provides to date according to its developer. Would it be feasible to implement the access to `window.history` for Violentmonkey too, so this userscript (and others that may depend on this API) can re-organize web pages as intended?

For more background to this usecase and the limitations of Violentmonkey as of right now:
https://github.com/Bl4Cc4t/GoodTwitter2/issues/96#issuecomment-641240621

**Comment by tophf** [comment] 2020-06-12 03:13
@spodermenpls, `window.history` is not related to the `history` permission which is for `chrome.history` API. As for the problem, that script's author can simply use the standard Firefox method: unsafeWindow.wrappedJSObject + exportFunction, [example](https://github.com/violentmonkey/violentmonkey/issues/997#issuecomment-637700732).

**Comment by spodermenpls** [comment] 2020-06-12 20:42
@tophf Thank you very much for being so kind and lending GoodTwitter2's author a hand with this issue, that was solved faster than I've imagined!

On a side note: Since I've been back using VM for this very userscript after 2.5 years of no need for it, I've been surprised to see that nobody has even tried maintaining the German locale, I've Iron Manned it in one sitting and updated/corrected about half of the entire thing. with Transifex not being too workflow-friendly compared to Crowdin, I might add.
