### ISSUE TITLE
2.12.2 break the sites

### ISSUE THREAD

**Issue by wvxwxvw** [violentmonkey/violentmonkey#730] opened 2019-11-26 09:09 UTC
GitHub - Unable to edit your posts in Issues.
Yandex Disk - Unable to go to folder / archive

**Comment by tophf** [comment] 2019-11-26 09:43
I can do both just fine. Add a complete instruction on how to reproduce the bug in a new browser profile.

**Comment by wvxwxvw** [comment] 2019-11-26 10:40
What instructions do you need?

Create a profile.
Install the extension.
Go to the sites specified  by me.
Try to perform the actions specified by me.

Do you want me to write more often? OK =)

**Comment by tophf** [comment] 2019-11-26 10:49
Try to be more cooperative otherwise I can't help because I already did exactly that and everything worked just fine for me.

**Comment by wvxwxvw** [comment] 2019-11-26 10:51
Firefox ESR 68.2 x64
I have a new version works exactly as I indicated. I roll back to the old version and everything works as it should.

**Comment by wvxwxvw** [comment] 2019-11-26 10:53
Well, wait for other reviews.

**Comment by tophf** [comment] 2019-11-26 10:54
If you don't want to provide all the info needed to reproduce the issue I'll close this report indeed and we'll wait for reports from more cooperative people.

**Closed** 2019-11-26 11:04 UTC
Labels: needs details, not reproducible

**Comment by wvxwxvw** [comment] 2019-11-26 11:55
Reproduced. Breaks the specified sites with the mode of injection "auto" and "page". Regardless of the activated scripts, you can do without scripts.

**Comment by tophf** [comment] 2019-11-26 11:58
I couldn't and still can't reproduce without any scripts. We've already got a helpful report in #733 which contains an exact instruction.
