### ISSUE TITLE
[BUG] Get stuck when calling GM.setValue the second time with different value.

### ISSUE THREAD

**Issue by cesaryuan** [violentmonkey/violentmonkey#2058] opened 2024-03-30 09:10 UTC
### Sequence of actions: 
1. install the following scripts
```
// ==UserScript==
// @name        Bug for GM.setValue
// @namespace   Violentmonkey Scripts
// @match       https://violentmonkey.github.io/api/gm/
// @grant       GM.setValue
// @version     1.0
// @author      -
// @description 2024/3/30 16:42:40
// ==/UserScript==

(async () => {
  console.log('test1');

  await GM.setValue('test', '1')

  await GM.setValue('test', '2')

  console.log('test2');

  await GM.setValue('test', '3')

  console.log('test3');
})()
```
2. open https://violentmonkey.github.io/api/gm/
3. console will only log `test1` without `test2` and `test3`.

#### Environment:
- OS: Windows
- Browser: Chrome 123.0.6312.86
- Violentmonkey Version: 2.18.0

**Comment by tophf** [comment] 2024-03-30 09:42
I can't reproduce the problem. I guess it might be #2028 which is fixed in Violentmonkey beta.

**Closed** 2024-03-30 09:43 UTC
Labels: bug
