### ISSUE TITLE
Add eslint in editor

### ISSUE THREAD

**Issue by alejandro5042** [violentmonkey/violentmonkey#993] opened 2020-05-20 16:36 UTC
# What is the problem?

TamperMonkey runs eslint in the editor, giving helpful tips on how you can improve your userscript.

### What is the expected result?

eslint in ViolentMonkey.

**Comment by tophf** [comment] 2020-05-20 16:37
Duplicate of #836.

**Closed by tophf** 2020-05-20 16:37 UTC
