### ISSUE TITLE
Export to zip not working when multiple scripts are installed

### ISSUE THREAD

**Issue by rayman89** [violentmonkey/violentmonkey#243] opened 2017-10-17 21:58 UTC
Export to zip is not working when multiple scripts are installed I'm on windows 7x64 using firefox 57 beta x64 ViolentMonkey version 2.8.13

**Comment by gera2ld** [comment] 2017-10-18 02:05
duplicate of #113 , I will reopen that one

**Closed by gera2ld** 2017-10-18 02:05 UTC
