### ISSUE TITLE
[Feature] add `data` section for `GM_notification` and move latter's implementation to Service Worker

### ISSUE THREAD

**Issue by helloworldSB** [violentmonkey/violentmonkey#1887] opened 2023-09-09 03:06 UTC
**Motivation**

I want to push a notification, then I write this.
```javascript
    function push(url, subject, title, icon, tag) {
        const option = {
            body: subject,
            data: {
                url
            },
            icon, tag,
            silent: config.silent,
            renotify: config.renotify
        };
        if (!config.silent) option.vibrate = true;

        const noti = new Notification(title, option);
        noti.onclick = function () {
            GM_openInTab(noti.data.url, {insert: false});
            noti.close();
        };
    }
```
The problem is: after closing the tab which the Script file runs, The `noti.data.url` will not be available, so the first argument `GM_openInTab` received is `null`.
`GM_notification` could not solve the problem because it doesn't support `data` section.
It seems that `GM_notification` has a similar implementation to my `push` function.

**Proposed Solution**

 move `GM_notification`'s implementation to Service Worker, and add `data` section for `GM_notification` API.

**Use Cases**

Push Notifications when a new post is sent in forum.

**Comment by gera2ld** [comment] 2023-09-09 03:34
I don't see why `data` is needed. Can you elaborate?

```ts
function push(...) {
  const data = { url };
  GM_notification({
    // ...
    onclick: () => {
      // use `data` here
    },
  });
}
```

**Comment by tophf** [comment] 2023-09-09 06:14
Moving it anywhere won't solve the problem and we can't move it anywhere else anyway, because it's not "placed" anywhere. You'll need to find another way to solve the problem. Currently it's unclear what happens without debugging your complete userscript that demonstrates the problem.

**Closed by tophf** 2023-09-09 06:14 UTC
Labels: enhancement

**Comment by helloworldSB** [comment] 2023-09-09 08:10
> I don't see why `data` is needed. Can you elaborate?
> 
> ```ts
> function push(...) {
>   const data = { url };
>   GM_notification({
>     // ...
>     onclick: () => {
>       // use `data` here
>     },
>   });
> }
> ```



> I don't see why `data` is needed. Can you elaborate?
> 
> ```ts
> function push(...) {
>   const data = { url };
>   GM_notification({
>     // ...
>     onclick: () => {
>       // use `data` here
>     },
>   });
> }
> ```

After reload the page, the old notification will destroyed, but the Notification from the System's notification center won't be closed, and it could not work properly (browser should open a page when the notification was clicked).

**Comment by helloworldSB** [comment] 2023-09-09 08:39
> Moving it anywhere won't solve the problem and we can't move it anywhere else anyway, because it's not "placed" anywhere. You'll need to find another way to solve the problem. Currently it's unclear what happens without debugging your complete userscript that demonstrates the problem.

```javascript
// ==UserScript==
// @name        New script - example.org
// @namespace   Violentmonkey Scripts
// @match       https://example.org/
// @grant       GM_notification
// @grant       GM_openInTab
// @version     1.0
// @author      -
// @description 2023/9/9 16:13:32
// ==/UserScript==

function parse_result() {
    let uri = "https://example.com/";
    // do some works
    return uri;
}

function main() {
    let uri = parse_result();
    if (uri != null) {
        GM_notification({
            text: "A new post found!!!",
            onclick: () => GM_openInTab(uri)
        });
    }
    setTimeout(main, 5000); // disabled for debugging
};

setTimeout(main, 5000);
```

1. Install the script
2. open [This site](https://example.org/)
3. wait until notification is shown
4. close the tab, then click the notification
5. Nothing will happend

But I want notification work, even if the tab where the UserScript runs is closed.

**Comment by tophf** [comment] 2023-09-09 08:44
I see, but this is the expected behavior, we can't change it, we can't run userscript code when its tab is closed.
