### ISSUE TITLE
script not working. but working in tampermonkey

### ISSUE THREAD

**Issue by zsedrrt543434gdsfv** [violentmonkey/violentmonkey#1452] opened 2022-01-21 11:19 UTC
### What is the problem?
script not working. but working in tampermonkey

### How to reproduce it?
1. run script on for example this url https://echo.msk.ru/programs/pastukhov/2968086-echo/
// ==UserScript==
// @name         echo.msk.ru text selection
// @namespace    Violentmonkey Scripts
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://echo.msk.ru/*
// @grant        none
// ==/UserScript==

var a = document.getElementsByClassName("typical")[0];
var b = a.cloneNode(true);
a.parentNode.replaceChild(b, a);

### What is the expected result?
the script expected to run. (it removes text selection popup script)
### What is the actual result?
in violentmonkey it does not run. in tampermonkey it runs. 

### Environment
- Browser: FF 93.0
- Violentmonkey version: v2.13.0
- OS: Win10

**Comment by tophf** [comment] 2022-01-21 11:30
This bug is already fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases). Meanwhile the workaround is to add this script in dashboard:

```js
// ==UserScript==
// @name   Violentmonkey 2.13.0 bug fix
// @grant  none
// @run-at document-start
// ==/UserScript==

```

**Closed by tophf** 2022-01-21 11:30 UTC

**Comment by zsedrrt543434gdsfv** [comment] 2022-01-21 11:44
Still not working. I tested it with 2.13.0.16 and your "Violentmonkey 2.13.0 bug fix" script added.

**Comment by zsedrrt543434gdsfv** [comment] 2022-01-21 11:51
Still not working. I tried it with 2.13.0.16 and you "Violentmonkey 2.13.0 bug fix" script added. No luck.

**Comment by tophf** [comment] 2022-01-21 11:56
I can't reproduce the problem: the script runs in beta as can be seen in the Violentmonkey popup menu.
Maybe you didn't install beta properly?

![image](https://user-images.githubusercontent.com/1310400/150523121-12c669d9-706f-4112-840a-36bbf4a07483.png)

See if you can reproduce the problem in a new clean browser profile.

**Comment by zsedrrt543434gdsfv** [comment] 2022-01-21 12:09
Yes I also see the script is activated. But it has no effect. Try to select couple of words from the text of the interview on the page https://echo.msk.ru/programs/pastukhov/2968086-echo/. You will get popup with fb and twitter icons. My script just block this behaviour. You can try to run script commands in console and then select text again popup will not be shown. In tampermonkey it works as it should. (script actually copy-past "interview text" part of the page and js script not copied with it)

**Comment by tophf** [comment] 2022-01-21 12:33
Your script prints an error: `a` is undefined both in Violentmonkey and Tampermonkey so it doesn't work. The fact that enabling Tampermonkey disables the buttons on the site is just an unrelated coincidence, which I won't investigate further because the script is making an assumption that `typical` class is present when the script runs, but actually it's incorrect: the element is added by the site asynchronously.

Try simply hiding the buttons:

```js
document.head.appendChild(document.createElement('style')).textContent = `
.tooltipster-default {
  display: none !important;
}
mark.contentshare {
  background: inherit;
}
mark {
  background: inherit;
  color: inherit;
  font-style: inherit;
  font-weight: inherit;
}
`;
```

**Comment by guga50** [comment] 2022-01-21 13:31
Script running in Tampermonkey:
// ==UserScript==
// @name         echo.msk.ru text selection
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://echo.msk.ru/*
// @grant        none
// ==/UserScript==

var a = document.getElementsByClassName("typical")[0];
var b = a.cloneNode(true);
a.parentNode.replaceChild(b, a);
b.parentNode.appendChild(document.createElement('style')).textContent = 'blah blah';

![Capture](https://user-images.githubusercontent.com/98158835/150535231-efee45a2-b3ca-404d-b0c3-7d2c5366745b.PNG)

in Violentmonkey there is no "blah blah"

**Comment by tophf** [comment] 2022-01-21 13:53
Your script works correctly for me in beta, both the original one and the new one.

P.S. I've investigated a little and found I was wrong about a mistake in the code: there was none and the error about the element was printed in an unrelated iframe. You can suppress the error by adding `// @noframes` after the `@grant none` line.
