### ISSUE TITLE
Why does not VM work on twitter?

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#487] opened 2018-12-19 06:18 UTC
Userscripts can not be executed on **twitter** and similar sites. Why?

![default](https://user-images.githubusercontent.com/33825590/50203087-6dcf4a00-0371-11e9-80cc-a7ba32e84e88.png)

**Comment by gwarser** [comment] 2018-12-19 09:32
https://violentmonkey.github.io/2018/11/23/inject-into-context/

**Comment by soviet-man** [comment] 2018-12-19 11:37
Thank you!

**Comment by gera2ld** [comment] 2018-12-21 02:01
CSP issue, duplicate of #408

**Closed by gera2ld** 2018-12-21 02:01 UTC
