### ISSUE TITLE
turkoptiscript doesn't work in violentmonkey

### ISSUE THREAD

**Issue by insanid** [violentmonkey/violentmonkey#248] opened 2017-10-26 08:14 UTC
### What is the problem?
The userscript turkoptiscript 1.0.0-rc4 does not work on https://worker.mturk.com with violentmonkey. The content that the script adds to the page does not appear next to the requester on the results.

### How to reproduce it?
1. Install turkoptiscript 1.0.0-rc4 from (https://turkopticon.info/install) raw: https://github.com/turkopticon/turkoptiscript/raw/master/dist/turkoptiscript.es6.user.js.
2. Log into https://worker.mturk.com
3. Click on HITs at top of page > Click on All HITs (a list of HITs will appear)

### What is the expected result?
Next to each of the listings is the name of the requester. turkoptiscript adds a circular icon with the words "TO" to the left of the requester name. Upon mouse over the circular TO icon a CSS popup appears with reviews extracted from https://www.turkopticon.info .

### What is the actual result?
The circular icon with the words "TO" is not appearing next to the names of the requesters. Because the icon is missing it is not possible to mouse over the icon to get reviews. violentmonkey is showing that the script is detected and loaded for the site, but its not modifying the page.

NOTE: The script is confirmed working on https://worker.mturk.com with tampermonkey
NOTE: This issue does not occur on https://www.mturk.com . The script is designed to work on both https://www.mturk.com and https://worker.mturk.com.

### Environment
- Browser: Firefox 57.0b11 (64-bit) || Chrome 62.0.3202.62 (Official Build) (64-bit)
- Browser version: Firefox 57.0b11 (64-bit) || Chrome 62.0.3202.62 (Official Build) (64-bit)
- Violentmonkey version: v2.8.13
- OS: Windows 10 Enterprise (64-bit) Version 1709 (OS Build 16299.15)

**Comment by gera2ld** [comment] 2017-10-27 14:54
Should have been fixed in violentmonkey/violentmonkey@4b52445 . I just tested it with the latest development version and it worked. I will release a new version soon.

**Comment by gera2ld** [comment] 2017-10-28 10:25
@insanid Does this work on latest version (v2.8.15)?

**Comment by insanid** [comment] 2017-10-28 10:55
@gera2ld I tried the new release (v2.8.15) in the same environment and it still didn't work for me :(

**Comment by gera2ld** [comment] 2017-10-28 11:28
That's weird, I have tested v2.8.15 on Firefox 56 / Nightly, Chrome 62, all works well.

**Comment by insanid** [comment] 2017-10-28 11:49
@gera2ld ill test again later today on a different machine. maybe its my profile.

**Comment by insanid** [comment] 2017-10-29 06:18
@gera2ld Tested on new profile in Firefox 75.0b12 (64-bit) OS: Windows 10 Enterprise (64-bit) Version 1709 (OS Build 16299.15) violentmonkey version: v2.8.15. Confirmed working. Issue resolved. Thank you for fixing the bug so quickly!

**Comment by gera2ld** [comment] 2017-10-29 06:44
So it still does not work with the old profile?

**Comment by gera2ld** [comment] 2017-10-30 14:19
Closing since it works, I just confirmed with a clean profile.

**Closed by gera2ld** 2017-10-30 14:19 UTC
Labels: bug

**Comment by insanid** [comment] 2017-10-30 19:58
@gera2ld The script is confirmed work on all profiles as of 4b52445. I said in error that it didn't work. I got the turkoptiscript issue mixed up with the Panda Crazy issue (which you recently fixed that bug in d902c71). I'd like to test the bux fixes you make in the main trunk, but I'm not terribly familiar with the build environment and process, so until I get that sorted out I'm relegated to using your releases.
