### ISSUE TITLE
Unviewable code when importing/editing userscript in Firefox Nightly on Android.

### ISSUE THREAD

**Issue by K-Visscher** [violentmonkey/violentmonkey#1287] opened 2021-05-30 19:14 UTC
First up, thanks for this extension and your hard work, it works (almost 😉) flawlessly on Android in Firefox Nightly!

### What is the problem?
When importing/editing a user script that is sufficiently large enough to require a user to scroll, some lines of codes aren't visible, nor is the user able to scroll towards the bottom of the script to reveal the disappeared lines of code.

As a workaround I've found that when searching for text, that's within the lines of code that aren't visible, the browser jumps to it, which reveals the missing lines of code.

I think this is mostly a cosmetic/css issue. 

### How to reproduce it?
1. Import a sufficiently large userscript in portrait orientation so that it requires scrolling.
2. Try to scroll to the bottom of the script.

### What is the expected result?
User should be able to scroll completely towards the last lines of code, making them visible.

### What is the actual result?
User isn't able to scroll completely towards the last lines of code,

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?
I haven't tried this, to be honest, I'm sorry. 

### Environment
- Browser: `Firefox Nightly`
- Browser version: `90.0a1 (build #2015813259)`
- Violentmonkey version: `v2.13.0` (latest release/build from AMO)
- OS: `Android 10`
- Device: `Xiaomi Mi A2 (1080x2160)`

**Comment by tophf** [comment] 2021-05-31 02:58
Definitely sounds like a bug in the browser because we're simply using CodeMirror for the editor. I don't have an Android anyway so I can't reproduce.

**Comment by gera2ld** [comment] 2021-05-31 03:10
I think this is a duplicate of #1249

**Closed** 2021-05-31 09:10 UTC
Labels: external
