### ISSUE TITLE
 Scripts don't load when using Firefox's "Never remember history"

### ISSUE THREAD

**Issue by Gepfiz** [violentmonkey/violentmonkey#186] opened 2017-08-22 00:32 UTC
### What is the problem?

When Firefox is set to "Never remember history" or "Always use private browsing", the installed scripts are automatically disabled and can't be enabled. The "installed scripts" page of the dashboard also keeps endlessly loading.

The same does not happen when opening a private tab from a default configured Firefox.

### How to reproduce it?
1. Open Firefox's privacy settings
2. Configure to never remember history

### Environment
- Browser: Firefox
- Browser version: 55.0.2 (64-bit)
- Violentmonkey version: 2.6.3
- OS: Windows 7 Professional

**Comment by gera2ld** [comment] 2017-08-22 01:33
duplicate of #169

**Closed by gera2ld** 2017-08-22 01:33 UTC
