### ISSUE TITLE
[Firefox Bug]Cookie is not sent with GM_xmlhttpRequest

### ISSUE THREAD

**Issue by machsix** [violentmonkey/violentmonkey#761] opened 2019-12-16 20:18 UTC
### What is the problem?

Cookie is not sent with GM_xmlhttpRequest in Firefox

### How to reproduce it?
1. Userscript
```js
// ==UserScript==
// @name New Script
// @namespace Violentmonkey Scripts
// @match *://www.google.com/*
// @grant GM_xmlhttpRequest
// ==/UserScript==

(function(){
  GM_xmlhttpRequest({
    url: "https://www.google.com",
    method: "GET",
    onload: (x) => {console.log(x)}
  })
})();
```

### What is the actual result?
With fiddler monitoring the package,

In Violentmonkey+Window Edge Dev, I get
![2](https://user-images.githubusercontent.com/28209092/70939837-1660ca00-2017-11ea-80b6-6ba801ad02be.PNG)
Clearly, a **default** cookie is sent

In Violentmonkey+Firefox, I get
![1](https://user-images.githubusercontent.com/28209092/70939885-31cbd500-2017-11ea-9081-9dabd9d42072.PNG)

No cookie is sent. 

The same thing happens with Tampermonkey. Any idea on how to fix it? I tried to add `document.cookie` to cookie jar. But it is not exactly the same as the default one.

**Comment by tophf** [comment] 2019-12-16 20:27
Duplicate of #606.

**Closed by tophf** 2019-12-16 20:27 UTC

**Comment by machsix** [comment] 2019-12-18 05:43
> 
> 
> Duplicate of #606.
> Already implemented in the upcoming version of Violentmonkey.

I side loaded the version you provided at https://github.com/violentmonkey/violentmonkey/issues/606#issuecomment-557890579 but it doesn't work.

The minimum script:
```js
// ==UserScript==
// @name        New script 
// @namespace   Violentmonkey Scripts
// @match       *://*/*
// @grant       GM_xmlhttpRequest
// @version     1.0
// @author      -
// @description 12/18/2019, 12:37:17 AM
// ==/UserScript==
(function(){
  GM_xmlhttpRequest({
    url: "https://v2ex.com/recent?p=2",
    withCredentials: true,
    method: "GET",
    onload: (x) => {console.log(x)}
  })
})();
```

I login at [https://v2ex.com](https://v2ex.com) and open link [https://v2ex.com/recent](https://v2ex.com/recent). The console doesn't show the doc of page [https://v2ex.com/recent?p=2](https://v2ex.com/recent?p=2). There is `你要查看的页面需要先登录` in the dom, which means `You need to login to view the content`

Fiddler also shows no cookie is sent.

![1](https://user-images.githubusercontent.com/28209092/71058911-4c916d00-212f-11ea-8533-7e72d3d5c3b7.PNG)

**Comment by tophf** [comment] 2019-12-18 06:09
> It seems withCredentials: true, is not needed.

It's only needed when the URL in gmxhr has a different *origin* to the tab's URL.
