### ISSUE TITLE
`@run-at document-start` 下的 `@require` 脚本无法使用 document.querySelector('head')

### ISSUE THREAD

**Issue by SublimeCT** [violentmonkey/violentmonkey#1292] opened 2021-06-13 01:57 UTC
### What is the problem?
`@run-at document-start` 下的 `@require` 脚本无法使用 `document.querySelector('head')`

![issue1.png](https://i.loli.net/2021/06/13/gO3vWylSrFJkpPh.png)
![issue2.png](https://i.loli.net/2021/06/13/F2WwnL6gTUKziJP.png)
![issue3.png](https://i.loli.net/2021/06/13/jAXboUieMQn1BNx.png)

### How to reproduce it?
1. install [this script](https://greasyfork.org/zh-CN/scripts/373457)
2. [click this link](https://blog.csdn.net/vinsuan1993/article/details/77144263)

### Environment
- Browser: `Firefox`
- Browser version: `89.0`
- Violentmonkey version: `2.13.0`
- OS: `MacOS`

**Comment by tophf** [comment] 2021-06-13 03:05
The problem is that the userscript is making incorrect assumptions about `document.head` being available but `@run-at document-start` **by definition** doesn't give a guarantee that `head` or `body` exist because this mode runs userscripts as early as possible, when only `document.documentElement` is guaranteed to be present. 

Old Violentmonkey was simply slower to inject userscripts whereas the new Violentmonkey is faster so now it implements userscript specification correctly.

The userscript can be fixed via the following:
* use `document.documentElement` instead of `document.head` or `document.querySelector('head')`
* use `document-body` instead of `document-start`.

**Closed by tophf** 2021-06-13 03:05 UTC
