### ISSUE TITLE
[Chromium] GM.xmlHttpRequest is very slow and buggy

### ISSUE THREAD

**Issue by AlttiRi** [violentmonkey/violentmonkey#1066] opened 2020-09-26 03:50 UTC
### What is the problem?

`GM.xmlHttpRequest` is very slow and buggy.

### How to reproduce it?
Use this script to download some file (30+MB) from a file hosting (sorry, no URL example, I will add it later (if you would still need))
```js
// ==UserScript==
// @name        New script - GM.xmlHttpRequest
// @namespace   Violentmonkey Scripts
// @match       <PUT_HERE_THE_ADDRESS>   // TODO: add a demo URL
// @grant       GM.xmlHttpRequest
// @version     1.0
// @author      -
// @description GM.xmlHttpRequest slow chrome
// ==/UserScript==

const UNSENT           = 0;
const OPENED           = 1;
const HEADERS_RECEIVED = 2;
const LOADING          = 3;
const DONE             = 4;
const xml = GM.xmlHttpRequest({
  method: "GET",  
  url: "<PUT_HERE_THE_ADDRESS>",    // TODO: add a demo URL
  onload: function(response) {
    console.log("---onload---");
    console.log(response);
    console.log("response.loaded", response.loaded);
    console.log("response.responseText.length", response.responseText.length);
    console.log("response.response.length", response.response.length);
  },
  onreadystatechange: function(response) {
   console.log("onreadystatechange", response.readyState, response, response.responseText.length);
    if (response.readyState === HEADERS_RECEIVED) {
        console.log(response);
        console.log(response.responseHeaders);
    }
  },
});
console.log(xml);
```

### What is the expected result?

`GM.xmlHttpRequest` works fast without freezing.

No problem in Firefox. And no problem with Tampermonkey _(but it has no `response.response` and `response.responseText === ""` for `onreadystatechange` event)_ _UPD: But it's normal for using with `responseType: "arraybuffer";_

### What is the actual result?

Downloading in the background script work absolutely OK (I checked it with DevTools). So it's the problem with the sending data to the content script.

With little files ~5 MB it works ~OK.
With files ~15 MB I works slow.
For file 20 MB + it begins to work very slow, and probably freezing (no progress). Also the extension start to lag (Can't immediately open the popup). Memory consuming is increasing.

### Environment
- Browser: Chrome, Opera.
- Browser version: Chromium 85 based
- Violentmonkey version: 2.12.7
- OS: Win 10

**Comment by AlttiRi** [comment] 2020-09-26 03:53
z

**Comment by tophf** [comment] 2020-09-26 04:01
Should be fixed in the upcoming [release candidate](https://github.com/violentmonkey/violentmonkey/releases), please test it.

**Comment by AlttiRi** [comment] 2020-09-26 10:32
Well, yeah, it works fast now, but... I think it also should give me the properly data.

```js
  onload: function(response) {
    console.log("---onload---");
    console.log(response);
    console.log("response.loaded", response.loaded);
    console.log("response.responseText.length", response.responseText.length);
    console.log("response.response.length", response.response.length);
  },
```

For example, for tiny file (110_299 bytes):
TM:
```js
response.loaded undefined
response.responseText.length 104446
response.response.length 104446
```

VM:
```js
response.loaded 110299
response.responseText.length 104446
response.response.length 104446
```

VM RC:
```js
response.loaded 110299
response.responseText.length 62009 // ???
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined // ???
```

**Comment by AlttiRi** [comment] 2020-09-26 10:37
For example, for bigger file (44_290_547 bytes):
TM:
```js
response.loaded undefined
response.responseText.length 41981609
response.response.length 41981609
```

VM (`onload` was not executed):
```js
```

VM RC:
```js
response.loaded 44290547
65470 // ???
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined // ???
```

**Comment by AlttiRi** [comment] 2020-09-26 10:39
It does not work as expected.
`response.responseText.length` is always ~65470 bytes.
And `response.response` was removed.

**Comment by AlttiRi** [comment] 2020-09-26 15:23
Using `responseType: "arraybuffer",` in `details` GM.xmlHttpRequest param helps.

**But only in RC version**:
```js
response.loaded 44290547
response.loaded ArrayBuffer(44290547) {}
```

In live version I get 
```js
response.loaded 44290547
response.loaded ArrayBuffer(0) {}
```

So _this_ bug now no so critical. But it exists.

---

But _the fixed bug_ is critical, I think **the fix should be releases as soon as possible**. No need to wait for a big release.

**Comment by tophf** [comment] 2020-09-26 16:46
That's a lot of comments but there's nothing I can do without a URL that exhibits the bugs that you observed because I can't reproduce this bug.

**Comment by tophf** [comment] 2020-09-26 16:49
I do see a bug with responseText.length though, gonna investigate.

**Comment by tophf** [comment] 2020-09-26 16:52
Ah, the bug is triggered by the presence of `onreadystatechange`, I'll fix it.

**Comment by AlttiRi** [comment] 2020-10-03 19:58
@gera2ld release date? https://github.com/violentmonkey/violentmonkey/issues/1071

I'm interested only in fixing of `GM_xmlHttpRequest` (and `GM_download` that in fact is almost the same thing in VM) that was fixed some time ago.

Currently (I use only `GM_xmlHttpRequest`): 
- VM does not download files over 30 MB.
- TM make the web page to significantly lag when it transmits the binary data from background script to the web page. Saving (not downloading) takes ~5 secs for 20 MB file and the page lags. For 100 MB file the page freezes for ~25 seconds.
- VM RC works OK, I can download large data, and I have no lags.

**Comment by AlttiRi** [comment] 2020-10-04 02:26
Damn, the RC version has the additional permission (`declarativeContent`), so I can't just replace the content (except `manifest.json`) of the live extension with the content of RC for "transparent force update". 
_(I do it not in Chrome, but Chromium)_

**Comment by tophf** [comment] 2020-10-04 04:07
Er? In Chrome/Chromium you can trivially install RC as an unpacked extension and use it instead.

**Comment by AlttiRi** [comment] 2020-10-04 07:41
If the permissions were the same I could replace the extensions files and have one extension with the same settings and auto-updating (when you finally release it). 
In comparison to installing RC as the additional unpacked extension.

Just a note.

**Comment by tophf** [comment] 2020-10-04 07:42
No, replacing doesn't work in Chrome/Chromium because it performs automatic verification of file contents for extensions installed from the web store. Installing a separate unpacked extension is the proper method, it's trivial and straightforward.

**Closed** 2020-10-04 11:22 UTC
