### ISSUE TITLE
[BUG] cant see edit button when hovering over scripts on expanded toolbar icon

### ISSUE THREAD

**Issue by rezad1393** [violentmonkey/violentmonkey#1520] opened 2022-07-03 05:21 UTC
- [ x] I have searched for existing issues that already reported this problem and found none

**Describe the bug**
click on violentmonkey
see the list of installed scripts 
cant see edit script or hamburger menu of script unless user knows where it is and click on it blindly. then they appear.

**Expected behavior**
they should be seen without user click on them first.

**Environment:**
- OS: linux
- Browser: firefox 102
- Violentmonkey Version: 2.13.0

**Comment by tophf** [comment] 2022-07-03 05:45
These buttons are shown automatically when you hover the line anywhere. However, on a touchscreen there's usually no way to hover, so we should always show the buttons in this case. On a normal desktop computer I'm not sure we should show the buttons. @gera2ld, WDYT?

**Comment by gera2ld** [comment] 2022-07-03 05:56
yeah that makes sense. I think we can show the buttons if touch events exist.

**Comment by rezad1393** [comment] 2022-07-03 06:03
when I open it  in firefox the button are not there 
but when I click on the approximate place of the edit button they appear and hovering over other scripts shows for them too.
I am on wayland kde linux.
maybe a wayland issue?

**Comment by gera2ld** [comment] 2022-07-03 06:09
@rezad1393 Do you mean the hovering only works after you click somewhere in the page?

**Comment by rezad1393** [comment] 2022-07-03 06:13
> @rezad1393 Do you mean the hovering only works after you click somewhere in the page?

on the popup page, yes
good catch.

**Comment by tophf** [comment] 2022-07-03 06:17
Sounds like a bug in Wayland or Firefox - it doesn't autofocus the popup.

BTW you can edit the script by right-clicking it, middle-clicking it, Ctrl-clicking it.

**Comment by tophf** [comment] 2022-07-03 13:49
@rezad1393, the workaround is to set `Custom CSS` in Violentmonkey options to this:
```css
.page-popup .submenu-buttons {
  display: flex !important;
}
```
@gera2ld, since this is the only page that hides buttons, maybe it's wrong and we should always show them? Or add an option in settings?

**Comment by gera2ld** [comment] 2022-07-09 14:52
Maybe we can show them all.
Just a bit concerned about too many buttons for a small popup page, which is why I hid them.

**Comment by tophf** [comment] 2022-07-13 10:55
Fixed in bd68576e.

**Closed by tophf** 2022-07-13 10:55 UTC
Labels: bug, external, ui

**Comment by rezad1393** [comment] 2022-09-17 23:06
is this fixed in new version?
because it is not fix on my firefox.

**Comment by tophf** [comment] 2022-09-18 07:07
Well, it means we didn't guess the cause of the problem right.
I don't have any new ideas yet so please keep using the CSS workaround.

**Comment by rezad1393** [comment] 2022-09-19 21:24
yes I may have to resort to that.
thank you for trying to fix this.
