### ISSUE TITLE
Find scripts menu item has broken highlighting in Firefox

### ISSUE THREAD

**Issue by Herohtar** [violentmonkey/violentmonkey#351] opened 2018-02-17 22:51 UTC
### What is the problem?
When you hover over the "Find scripts for this site" menu item, then move to another item, parts of the menu item remain highlighted.

### How to reproduce it?
1. Open Firefox
2. Click the Violentmonkey icon in the toolbar
3. Hover over the "Find scripts for this site" menu item
4. Move the mouse to a different menu item

### What is the expected result?
Menu item should return to normal non-highlighted state

### What is the actual result?
Parts of the menu item return to the non-highlighted color, while others remain highlighted.
![image](https://user-images.githubusercontent.com/10427164/36346365-bbd974d2-1402-11e8-8ff1-610fa0ba2b94.png)

### Environment
- Browser: Firefox
- Browser version: 59.0b10 (64-bit)
- Violentmonkey version: 2.8.28
- OS: Windows 10

**Comment by gera2ld** [comment] 2018-02-20 14:26
Duplicate of #328 , it's just normal CSS and Firefox does the rendering. It's more like a Firefox issue.

**Closed by gera2ld** 2018-02-20 14:26 UTC
