### ISSUE TITLE
Violentmonkey does not work with disabled cookies

### ISSUE THREAD

**Issue by viliampucik** [violentmonkey/violentmonkey#169] opened 2017-08-08 19:14 UTC
### What is the problem?

Violentmonkey dashboard and userscripts, which do not use cookies, do not work when cookies are disabled in Firefox.

### How to reproduce it?
1. Install Violentmonkey.
2. Disable cookies: Preferences -> Privacy -> uncheck Accept cookies from sites.
3. Add exception for Violentmonkey extension: -> Exceptions -> moz-extension://0d0ae898-a4ca-465b-8056-34a1055610c3 -> Allow.

### What is the expected result?

Dashboard is visible, userscripts are executed.

### What is the actual result?

Dashboard is blank, no userscripts are executed.

### Environment
- Browser: Firefox
- Browser version: 54
- Violentmonkey version: v2.6.3
- OS: Linux

**Comment by gera2ld** [comment] 2017-08-09 01:45
Are you sure the issue is related to whether cookies are accepted? I just tested and it worked for me no matter whether the cookies are accepted.
Something more, what do you mean by "dashboard is blank", nothing or frames shown but no scripts?

**Comment by viliampucik** [comment] 2017-08-09 10:16
Actually today I found out that after upgrading to Firefox 55 and re-enabling already installed extensions then Violentmonkey dashboard and scripts started to work without any issue.

**Comment by gera2ld** [comment] 2017-08-15 07:02
fixed in v2.8.0

**Closed by gera2ld** 2017-08-15 07:02 UTC

**Comment by mathew832** [comment] 2017-08-15 14:19
Same issue. This extension isn't the only one, it also affects the few other addons I use like Hoverzoom, Stylus and a couple others I tried.
