### ISSUE TITLE
badge shows no scripts after clicking on suggested Youtube video but script is active (Firefox)

### ISSUE THREAD

**Issue by kkot** [violentmonkey/violentmonkey#365] opened 2018-03-04 08:14 UTC
### What is the problem?

I have an userscript working on youtube. When I open youtube first time number of running scripts in the badge is 1 (correct). When I click on another suggested video then badge doesn't show any scripts but it still running.

### How to reproduce it?
1. Create any userscript that works on youtube.com
2. Open youtube.com
3. Switch to another video by clicking suggested one.

### What is the expected result?

After 3. badge still shows 1 because the script is running.

### What is the actual result?

After 3. badge shows no script is running.

![obraz](https://user-images.githubusercontent.com/1009806/36943519-24bf2238-1f8b-11e8-8f3b-5be4cb770c65.png)

### Environment
- Browser: Firefox (I checked on Chrome an it works fine there)
- Browser version: 58
- Violentmonkey version: 2.8.29
- OS: Win 10

**Comment by gera2ld** [comment] 2018-03-15 01:59
This should be an issue to Firefox.
I can reproduce it in Firefox 59.0b and it seems to be fixed now in Firefox 60.0b3.

**Closed by gera2ld** 2018-03-15 01:59 UTC
