### ISSUE TITLE
support check for update for userscript from local http server

### ISSUE THREAD

**Issue by orionlee** [violentmonkey/violentmonkey#1020] opened 2020-07-12 16:53 UTC
### What is the problem?
When installing a userscript a local http server (the main workaround of installing local script on Firefox), the installed script doesn't support check for update. Users have to manually re-enter the script's URL in the Download URL of the script's settings.

### How to reproduce it?
1. Assume there is a local user script available at http://localhost:8000/lib/acme.user.js
2. Open the script in the browser
3. Click Confirm Installation to install the script.
4. In ViolentMonkey's script list, users can not check for update. (without manually entering Download URL in the settings)

The check for update is grayed out:
![image](https://user-images.githubusercontent.com/250644/87252115-8278a480-c425-11ea-8d1f-2e437ab1f2a8.png)

### What is the expected result?
- Violentmonkey should be able to check for update of the installed userscript.

### Environment
- Violentmonkey version: 2.12.7

**Comment by tophf** [comment] 2020-07-12 19:45
I guess we can save a `localhost` URL as the downloadURL in case this script is installed for the first time, @gera2ld?

**Comment by gera2ld** [comment] 2020-07-13 02:16
Because the local URL is supposed to be used for development temporarily, and it's not portable, making the sync service or export useless.

For instance, if I install a script from http://localhost:8080, and someday I start another project at http://localhost:8080 and create another script (this is quite common if we create projects from common generators), then all scripts installed locally will be updated to the last one developed at http://localhost:8080.

I'm wondering why this feature is required, do you have such a server started locally all the time? For development purpose please use **track local file** feature as described [here](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/).

**Comment by tophf** [comment] 2020-07-13 17:04
I see. I'd say this is a wontfix then. What we could do is probably embed the instruction into Violentmonkey so it becomes translatable, add a link to it in the installer UI, and always show the options when installing since there are only two.

**Comment by orionlee** [comment] 2020-07-13 18:27
I know I miss something. localhost will break general violentmonkey sync, though not my specific use case. 

FYI, my use case is pushing updates for my tablet-specific userscript from my desktop to the android tablet (using Firefox, so tracking local file is not an option).

1. I modify and test a script on my desktop, and save the script that is automatically synced to Google Drive.
2. The script is synced to my tablet (I use a third-party app that sync a bunch of different files, including my userscripts)
3. To pickup the changes, I started a http server on my tablet, and clicked check for update on violentmonkey. Firefox can't track local file changes.

**Comment by tophf** [comment] 2020-07-13 18:28
FWIW the upcoming [release candidate](https://github.com/violentmonkey/violentmonkey/releases) will be able to track local file changes in FF.

**Comment by orionlee** [comment] 2020-07-13 18:35
A possible (very loosely related) bug when I poked around the codes. It seems like @downloadURL in the metablock is ignored. The codes make use of it in various place (`meta.downloadURL`), but the parsing of the metablock always ignore downloadURL.

https://github.com/violentmonkey/violentmonkey/blob/v2.12.7/src/background/utils/script.js#L67-L70

https://github.com/violentmonkey/violentmonkey/blob/ebc85a79077de64fa8b45ce4cb379b3471ae3d11/src/background/utils/script.js#L67-L70

**Comment by tophf** [comment] 2020-07-13 18:47
>It seems like @downloadURL in the metablock is ignored

That definitely recognizes and stores `downloadURL`. If you can demonstrate the opposite please open a bug report with a method to reproduce the bug, preferably in a portable browser so that no about:config or flags affect the case.

**Comment by orionlee** [comment] 2020-07-13 22:24
I think the issue can be closed - it doesn't look like there is much can be done.

Tracking local file changes in Firefox would be convenient, but it doesn't exactly address my use case as it only works when file installation window is open. 

To address the use case, violentmonkey needs to be able to check for update against the local file without requiring file installation window. Browser don't allow it. Plus it will run into the sync issues @gera2ld mentioned.

**Closed** 2020-07-13 22:33 UTC
Labels: discussion
