### ISSUE TITLE
user script inject2download does not work well since 2.8.7 update with firefox 57 for android

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#198] opened 2017-09-03 20:42 UTC
https://greasyfork.org/en/scripts/18671-inject2download 
this user script after updating to version 2.8.7(from 2.6.3) work really bad and unreliably with latest firefox 57 for android(mac os version works well) 
it often wont show media url download(as it is supoposed to ) can someone tell me why?
reverting to version 2.6.3 everything works well

**Comment by ale82to** [comment] 2017-09-13 00:22
come one will someone look into this issue!!??

**Comment by gera2ld** [comment] 2017-09-13 02:00
duplicate of #208

**Closed by gera2ld** 2017-09-13 02:00 UTC
