### ISSUE TITLE
Doesn't work parser Yandex search

### ISSUE THREAD

**Issue by birykvlad** [violentmonkey/violentmonkey#397] opened 2018-04-19 05:45 UTC
There is a script that parse search results Yandex (https://yandex.ru) and produces links at the bottom of the page. In Violentmonkey versions 2.9 and 2.9.1, it stopped working. In the Greasemonkey works correctly.

Windows 10 x64
Firefox 59.0.2
In attach sript and screenshot
[j.SERParser.user.zip](https://github.com/violentmonkey/violentmonkey/files/1926766/j.SERParser.user.zip)
![2018-04-19 08 4151](https://user-images.githubusercontent.com/32539665/38973336-fc1178ee-43ad-11e8-8ce7-36172a1e49fc.png)

**Comment by gera2ld** [comment] 2018-04-19 06:58
Duplicate of #385

**Closed by gera2ld** 2018-04-19 06:58 UTC
