### ISSUE TITLE
听说chrome不一定要禁用啦.....

### ISSUE THREAD

**Issue by 990721830** [violentmonkey/violentmonkey#514] opened 2019-02-12 08:45 UTC
![7 353i 3u6 hli cxq s](https://user-images.githubusercontent.com/25548230/52622708-75305100-2ee5-11e9-9a85-a3634490ba80.png)
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/hQeJzPbG-js
快去围观惹....

**Comment by gera2ld** [comment] 2019-02-27 11:51
duplicate of #505

**Closed by gera2ld** 2019-02-27 11:51 UTC
