### ISSUE TITLE
Scripts stopped working after latest update

### ISSUE THREAD

**Issue by Symbai** [violentmonkey/violentmonkey#254] opened 2017-10-28 11:55 UTC
### What is the problem?

After installed the 2.8.14 update **all** my scripts have stopped working. Never had any issue before.
The script shown as active on the depending sites but there is no effect. I've tried multiple scripts for multiple sites  to make sure it's not a script or site issue.

I've also installed latest FF beta and violentmonkey on a second computer and successfully reproduced it.

I've installed Tampermonkey and Greasemonkey Alpha and noticed the scripts were working fine with those addons. So it definitely must be something you did in Violentmonkey update.

### Environment
- Browser: Firefox
- Browser version: 57.0b12
- Violentmonkey version:  2.8.15
- OS: Windows 10

**Comment by gera2ld** [comment] 2017-10-28 12:16
v2.8.15 should have fixed the problem

**Comment by Symbai** [comment] 2017-10-28 13:32
It did not that's why I decided to report this bug.
Switched to 2.8.13 and scripts are working again.

From 2.8.13 upgraded to 2.8.15 and scripts stopped working.
Downgraded from 2.8.15 to 2.8.13 and they are working again.

**Comment by gera2ld** [comment] 2017-10-28 13:48
Do your scripts have unicodes in them?

**Comment by Thorin-Oakenpants** [comment] 2017-10-28 17:31
side note: I have one script and it is working - but noticed that in about:debugging that VM shows the following error

> Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.

**Comment by Symbai** [comment] 2017-10-28 20:02
No unicode, this is how a simple script looks like which doesn't work since 2.8.14 version:

```
// ==UserScript==
// @name        test
// @namespace   test
// @include     https://www.test.com/test.asp*
// @version     1
// @grant       none
// ==/UserScript==

var links = document.getElementsByTagName('a')
for (var i=0; i < links.length; i++) {
  if (links[i].getAttribute("href").indexOf("-test") !== -1) {
   var textX = document.createTextNode(links[i].getAttribute("href").replace("test.asp?titleID=", ""));
    if (links[i].parentNode.getAttribute("style").indexOf("background-color: #F2A22F") !== -1) {
      links[i].setAttribute("style", "color: #000");
    }   
  }
}
```

**Comment by gera2ld** [comment] 2017-10-29 03:14
@Thorin-Oakenpants That does not matter, FF will ignore properties it does not support at the moment.

@Symbai I tested the script above on a freshly installed FF57b12 with VM 2.8.15 and everything works well. Could you please look into the logs in development tool or `about:debugging`? And please note that v2.8.14 is buggy on Firefox, please make sure you are using v2.8.15.

**Comment by Burnyx** [comment] 2017-10-29 05:35
Still don't work after v2.8.15 for me either. Example: https://github.com/ccd0/4chan-x still won't work.

**Comment by gera2ld** [comment] 2017-10-29 06:26
@Burnyx All scripts don't work or just some of them don't work?

**Comment by Cormak** [comment] 2017-10-29 08:07
2.8.14, 2.8.15, and 2.8.16 all break 4chan X + Oneechan for me on Firefox 56.0.2

Rolling back to 2.8.13 fixes it.

**Comment by Toora** [comment] 2017-10-29 08:41
I have no issues with ccd0's 4chan X on 57b12 (Win 10) using 2.8.16.

**Comment by Burnyx** [comment] 2017-10-29 09:20
@gera2ld All.

**Comment by Symbai** [comment] 2017-10-29 12:48
@gera2ld 

Well I'm not a developer so I don't really know how to do the debugging/log stuff (could you please tell me what to do in case this information isn't what you were looking for?)

I've switched to about:debugging and activated debugging for addons. Then I visited a website where the script isn't applied switch back to about:debugging tab and on Violentmonkey there was this information:

`Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.`

I've upgraded from 2.8.13 directly to 2.8.15 using the auto update in FF.

**Comment by gera2ld** [comment] 2017-10-30 03:58
Thank you @Symbai , the messages above are normal.
Can you post the log info in a page that has such issues? Right click on a page, click 'Inspect Element', then switch to 'Console' tab, there are the log lines.

**Comment by Symbai** [comment] 2017-10-30 12:17
These two lines show up on 2.8.14 and newer in the console:

```
Loading failed for the <script> with source "blob:*website url*".
Content Security Policy: The page’s settings blocked the loading of a resource blob:*website url*  ("script-src *website url* 'unsafe-inline' 'unsafe-eval' https://www.google.com").
```

**Comment by gera2ld** [comment] 2017-10-30 13:40
@Symbai Oh I see, that is the problem, the CSP issue.

**Comment by gera2ld** [comment] 2017-10-30 14:08
Reproduced by using a clean profile. (It's strange that I could not reproduce it before when using a shared profile from v58.)

Duplicate of #173, should work since Firefox v58.

It should work for other pages without CSP limitation, and even v2.8.13 should not work for this page. If so, this is a known issue and won't-fix. Can you confirm? @Symbai

**Comment by Symbai** [comment] 2017-10-30 15:55
I can confirm the script is working again on FF58. Guess that means I have to stay on 2.8.13 with FF57 until FF58 becomes beta.

**Comment by gera2ld** [comment] 2017-10-30 16:36
I think 2.8.13 is almost the same as 2.8.15 / 2.8.16 on FF57. I don't think 2.8.13 has worked before on that page with CSP limitation, due to a known issue. Closing since we have nothing to do to this now.

p.s. Firefox profile is confusing, a clean profile may solve strange problems. 😄

**Closed by gera2ld** 2017-10-30 16:36 UTC
Labels: bug

**Comment by rezad1393** [comment] 2017-11-13 21:47
this bug occurs for me too.
this is maybe the commit that cause this
 [ use src with Blob for injection ](https://github.com/violentmonkey/violentmonkey/commit/796cddd9f19b1b627a7f4e2071e96d766d76eef4)
