### ISSUE TITLE
GM_setClipboard is broken in 2.12.*

### ISSUE THREAD

**Issue by CrendKing** [violentmonkey/violentmonkey#700] opened 2019-11-09 19:30 UTC
### What is the problem?
GM_setClipboard is not working in 2.12.*. Not sure if any other GM_* is broken too.

### How to reproduce it?
1. Install 2.12.0 or 2.12.1.
2. Write a script with one liner like `GM_setClipboard('hello', 'text/plain')`. Do not forget about `@grant GM_setClipboard`.
3. Ctrl+V

### What is the expected result?
Clipboard content should be replaced with "hello"

### What is the actual result?
Clipboard content is untouched.

### Environment
- Browser: Firefox
- Browser version: Firefox 71 beta 8
- Violentmonkey version: 2.12.*
- OS: Windows

**Comment by tophf** [comment] 2019-11-09 19:37
Duplicate of #685.

**Comment by CrendKing** [comment] 2019-11-09 23:15
Sorry for the duplicate. I only searched opened issues.

**Comment by tophf** [comment] 2019-11-13 07:53
While waiting for a fixed release, you can install the old version of Violentmonkey. Export your settings first, uninstall the current version, install the previous version 2.11.2 from https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/ and then import the settings.

**Closed** 2019-11-17 08:19 UTC

**Comment by fazen** [comment] 2020-03-20 10:38
For me this is working (clipboard contains "test"):
```
GM_setClipboard("test")
GM_setClipboard("test". "text/plain")
```
And this is not working (clipboard result is empty):
```
GM_setClipboard("<a href='https://example.com'>visit example.com</a>", "text/html")
```

### Environment
- Browser: Firefox
- Browser version: 74.0 (64 bit)
- Violentmonkey version: v2.12.7
- OS: Ubuntu 18.04.4 LTS

**Comment by tophf** [comment] 2020-03-20 11:02
Setting HTML also doesn't work in Chrome. Digging further [reveals](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/clipboard/data_transfer.cc;l=209;drc=d9b91db0b32bcaed524db17b05f614c7e86326bc?sq=package:chromium) it's per spec, at least in Chrome so I guess it's the same reason in FF.
