### ISSUE TITLE
2.8.20 regression from 2.8.19

### ISSUE THREAD

**Issue by Luke-Baker** [violentmonkey/violentmonkey#292] opened 2017-11-22 16:33 UTC
### How to reproduce the problem
1. Install this test script:
```
// ==UserScript==
// @name           2.8.20 regression test
// @namespace      violentmonkey.scripts
// @include        https://upload.wikimedia.org/*.JPG
// @run-at         window-load
// @grant          none
// ==/UserScript==

var fn = window.location.href.slice(window.location.href.lastIndexOf("/")+1);
var img = document.querySelector('body > img:only-child');
if (img) console.info("NO EL: Yep, there's an image at .../"+fn);
else console.error("NO EL: Nope. No image found at.../"+fn);

function logDoc() {
  if (img) console.info("W/ EL: Yep, there's an image at .../"+fn);
  else console.error("W/ EL: Nope. No image found at.../"+fn);
}

window.addEventListener("load",logDoc,false);
```
2. Open the Browser Console.
3. [Open this image](https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/RedPandaFullBody.JPG/800px-RedPandaFullBody.JPG).

### What is the expected result?
Whether with a document event listener or without, the script finds the img element and logs a message to that effect to the console. This works in version 2.8.19.

### What is the actual result?
The script doesn't find the img element and logs the failure to the console.

### Environment
- Browser: Firefox Nightly
- Browser version: 59.0a1 build 20171122103138
- Violentmonkey version: 2.8.20
- OS: Windows 10 x64

**Comment by gera2ld** [comment] 2017-11-23 02:23
That's interesting, when the script is being executed, there is a `<script>` element appending to the body.
In v2.8.14-2.8.19, this script works due to the change of script injection way, which leads to some other problems.
I think this is the expected behavior, though it could be changed.
Even if Violentmonkey does not append the `<script>` element to `<body>`, many other scripts and extensions, as far as I know, append elements to it. So it is very likely to see extra elements on `<body>`. I don't think it a good idea to select an element with `body > *:only-child`.

**Comment by gera2ld** [comment] 2017-11-23 02:28
BTW, with a document event listener, the demo should work, but you need to find the `img` in the event listener:
```js
function logDoc() {
  // this line is added
  var img = document.querySelector('body > img:only-child');

  if (img) console.info("W/ EL: Yep, there's an image at .../"+fn);
  else console.error("W/ EL: Nope. No image found at.../"+fn);
}
```

**Comment by Luke-Baker** [comment] 2017-11-23 12:21
> BTW, with a document event listener, the demo works, but you need to find `img` in the event listener:

In 2.8.20, what's inside the event listener works the first time, before the image has been cached. But hit F5 once every few seconds and it stops working after about the 3rd–6th time. Of course, I don't literally mash refresh on already-loaded images; my point is that it's unreliable.

> I don't think it a good idea to select an element with `body > *:only-child`.

I need to resize images that are smaller than the window. Therefore I need to run the script on single images, once they've fully loaded, so their dimensions are known. For reasons not worth getting into, I can't be specific enough in `@include/@match`. If you have any alternate ways to go about it, I'm open to suggestions. Outside of an event listener, this seems to fare better in 2.8.20:
```JavaScript
var ss = document.styleSheets;
var im = document.images;
if (ss[1].href.indexOf("TopLevelImageDocument.css") != -1) console.info(im[0].src);
```
But the resizing portion fails on certain images when several are loaded into tabs. I'm not sure what goes wrong there. I only know it also happened in 2.8.19 but not Greasemonkey Legacy (haven't tried the new one). I guess it tries to act before the dimensions are known, which an event listener would solve, but since the event listener itself is unreliable… I'm at a loss. I would've thought `@run-at window-load` would be enough.

**Comment by gera2ld** [comment] 2017-11-23 17:08
Violentmonkey does not support `@run-at window-load`, it falls back to `@run-at document-end`, so perhaps you need to check if a listener is needed:

```js
if (document.readyState === 'complete') resizeIt();
else window.addEventListener('load', resizeIt, false);
```

Closing since this seems to be related to the code itself rather than a bug of Violentmonkey.

**Closed by gera2ld** 2017-11-23 17:08 UTC

**Comment by Luke-Baker** [comment] 2017-11-30 16:51
Worked in previous version → User's script must be to blame :ok_hand:
