### ISSUE TITLE
[BUG] File Locked Due to Overriding

### ISSUE THREAD

**Issue by cyfung1031** [violentmonkey/violentmonkey#1902] opened 2023-09-22 09:59 UTC
Finally I encounter the file locking issue in the latest BETA v2.15.4

The bug is that, the file is locked and even I just type an enter it will popup that the script is already installed.
even there is no edit, just check / uncheck the setting, the popup will come when i click the save button

### Sequence of actions: 

( I am not sure the exact steps for reproducing the bug, but i believe that...)

1. You have two scripts with different names
2. You incorrectly copied script B into script A via editor and save
3. Message is shown and you try to revert
4. Now script A is reverted without issue
5. Then go to script B and you would find that script B is "locked"

(The only thing I am sure is that, you have to wrongly paste some invalid code to another script file before. That file could have no issue now but another script would be locked)

### Problem: 

The script is locked

### Expected result:  

No bug

#### Devtools console contents:

No message

#### Environment:
- OS: MacOS
- Browser: Brave with Chrome 117 
- Violentmonkey Version: BETA v2.15.4

## Video

https://github.com/violentmonkey/violentmonkey/assets/44498510/046d8858-8bfa-41fc-b4ed-17483b7b949e

## Remarks
After video is recorded, the file gets unlocked. I don't know how, but seems better in v2.15.4.

**Comment by tophf** [comment] 2023-09-22 10:18
To clarify, the problem is that the alert is so big that the OK button is invisible and you can't press it to dismiss the dialog and continue editing. The fix would be for us to limit the displayed text both internally and visually via max-height and overflow.

**Comment by cyfung1031** [comment] 2023-09-22 10:30
> To clarify, the problem is that the alert is so big that the OK button is invisible and you can't press it to dismiss the dialog and continue editing. The fix would be for us to limit the displayed text both internally and visually via max-height and overflow.

It can be dismissed when i click outside the dialog.

The bug is that, the file is locked and even I just type an enter it will popup that the script is already installed.
even there is no edit, just check / uncheck the setting, the popup will come when i click the save button

**Comment by tophf** [comment] 2023-09-22 10:37
So the alert is shown even if you don't press the Save button or the hotkey Cmd-S?

**Comment by cyfung1031** [comment] 2023-09-22 10:40
> So the alert is shown even if you don't press the Save button or the hotkey Cmd-S?

I just open the editor for the existing script. 
As long as the Save button can be clicked (due to I typed a space in the editor, or due to setting changed)
the save action (by click "Save" or hotkey Cmd-S) will show this alert.

**Comment by tophf** [comment] 2023-09-22 16:36
@F9y4ng you're commenting in the wrong bug report. The correct one is #1901 where I explained the reason. When we change the way our update works we will change the behavior of editing as well. Not the other way around.

**Comment by cyfung1031** [comment] 2023-09-22 16:45
@tophf 
Just found a 100% reproducible way. I tried in Firefox and give the same bug.


## Video 01 - Prepare Two Scripts

https://github.com/violentmonkey/violentmonkey/assets/44498510/7ef3eff5-b9f2-47ee-b43d-1573077ae3a1

1) Just download two scripts from internet.
2) Open the editor to change the content into `console.log("script A");` and `console.log("script B");` separately.
3) Change the metablock to make sure it can be run in a web page.
4) Find a random page and check the console log. both "script A" and "script B" will be logged.

(In the video I just captured the main window. actually I opened inspection window to see the result.)
This is to make sure that both are downloaded from internet, modified, and ran once on any page.

## Video 02 - Test Now

https://github.com/violentmonkey/violentmonkey/assets/44498510/6e604c54-44d7-4940-8aba-b071723932c7


### 02a
1) Go back to the script B file.
2) Copy Script B (Ctrl-A + Ctrl-C)
3) In the same page, close the current editor, open Script A
4) Select all, Paste, and Save
5) Error is Shown - this is correct because we already have Script B.
6) Undo by Ctrl-Z (this is a little bit different from Chrome. In Chrome, Ctrl-Z twice to revert back to Script A code)
7) Save

### 02b
1) Go to Script B
2) Try Edit
3) Unable to Save
4) Revert back to original 
5) Still Unable to Save

Then do some other things to see...
like toggle the individual scripts, toggle the entire violentmonkey....
you can see the bug is still there.

The only way is to remove Script A.
now Script B can be edited.

But once Script A is back,
Script B become locked again.

**Comment by F9y4ng** [comment] 2023-09-22 17:07
> @F9y4ng you're commenting in the wrong bug report. The correct one is #1901 where I explained the reason. When we change the way our update works we will change the behavior of editing as well. Not the other way around.

I don't think so.

When I create a new script locally and save to close it , and then start testing it, I can't even edit the code again and it requires me to close the update before I can edit it, which is problematic in itself. you can try creating a new script with the following code. This feature setting is terrible.

```js
// ==UserScript==
// @name         test edit
// @version      0.1
// @author       You
// @description  create new script but i can't edit it.
// @namespace    test
// @updateURL    https://example.com/test.meta.js
// @downloadURL  https://example.com/test.user.js
// @match        *://*/*
// @grant        none
// ==/UserScript==

console.log("test")
```

**Comment by F9y4ng** [comment] 2023-09-22 17:22
> @F9y4ng you're commenting in the wrong bug report. The correct one is #1901 where I explained the reason. When we change the way our update works we will change the behavior of editing as well. Not the other way around.

Oh, I replied on the wrong ISSUE.😅

**Comment by cyfung1031** [comment] 2023-09-22 18:35
Just noticed that I use the v2.15.0 version for Firefox.

Just downloaded a fresh Firefox developer version to install the beta v2.15.4


https://github.com/violentmonkey/violentmonkey/assets/44498510/ac26baa2-a33f-449a-8ca7-f4d6a19002b5

Seems like editing script A also help.

**Comment by tophf** [comment] 2023-09-25 18:02
Can you reproduce it in the new beta 2.15.5?

**Comment by cyfung1031** [comment] 2023-09-26 12:09
> Can you reproduce it in the new beta 2.15.5?

[screen-capture(8).webm](https://github.com/violentmonkey/violentmonkey/assets/44498510/a0f77937-d82e-4fc0-b3bc-d116076f1532)

Same issue, and the code editor colors are ugly and sometimes light theme sometimes dark theme

**Comment by tophf** [comment] 2023-09-26 12:19
Thanks, I'll investigate.

> editor colors are ugly and sometimes light theme sometimes dark theme

I can't reproduce it. I think the only way it can happen is a bug in the browser.
Does it help if you change UI theme in the options?
![image](https://github.com/violentmonkey/violentmonkey/assets/1310400/f8fbeecc-5b54-4e29-8c4d-2df1df3e9ddb)

**Comment by cyfung1031** [comment] 2023-09-26 12:35
> Thanks, I'll investigate.
> 
> > editor colors are ugly and sometimes light theme sometimes dark theme
> 
> I can't reproduce it. I think the only way it can happen is a bug in the browser. Does it help if you change UI theme in the options? ![image](https://user-images.githubusercontent.com/1310400/270652407-f8fbeecc-5b54-4e29-8c4d-2df1df3e9ddb.png)

Yes, it helps.
after few operations with violentmonkey, both script editor become light theme under default.

I think it is a bug?
If ui theme is dark, the editor theme (auto/default) should be also dark?

**Comment by tophf** [comment] 2023-09-26 13:06
As I said, it works correctly for me, so I can't see what might be causing the problem in your case.

**Comment by tophf** [comment] 2023-09-26 13:16
Does it happen only in Firefox? It has a known bug with theme detection.

**Comment by cyfung1031** [comment] 2023-09-26 13:23
> So I guess it may be OS-specific, I'm on Windows.

I guess so but it can detect correct in ui theme auto !?

**Comment by tophf** [comment] 2023-09-26 13:25
Do you mean when it's `auto` there's no bug?

**Comment by cyfung1031** [comment] 2023-09-26 13:28
> Do you mean when it's `auto` there's no bug?

If it is due to the bug that violentmonkey cannot detect the system setting, 
both ui and editor shall be same either dark or light.

but now, the ui mode (auto) can change as the system dark/light changes, and editor theme (default) remains the same regardless the ui theme (system dark/light)

**Comment by cyfung1031** [comment] 2023-09-26 13:33
<img width="653" alt="Screen Shot 2023-09-26 at 22 33 29" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/782b9f6f-e6b2-4354-b268-9af6b57f6558">

UI Theme auto
Editor Theme Default

**Comment by tophf** [comment] 2023-09-26 13:39
I still don't understand what happens as everything works correctly here. The `Editor theme` was never linked to `UI theme`, it was always independent by design and it didn't change and won't change.

**Comment by tophf** [comment] 2023-09-26 13:41
In other words if your `Editor theme` is not `(Default)` then the bug was in earlier versions of Violentmonkey as it didn't respect the option.

**Comment by cyfung1031** [comment] 2023-09-26 13:45
> In other words if your `Editor theme` is not `(Default)` then the bug was in earlier versions of Violentmonkey as it didn't respect the option.

Here is the 2.15.0 vs 2.15.5
Which one is your intended design?

[screen-capture(10)-reformatted-00.00.01.543-00.00.39.951.webm](https://github.com/violentmonkey/violentmonkey/assets/44498510/16c1aefb-7a4d-47f0-9ab0-6af062611063)

**Comment by tophf** [comment] 2023-09-26 13:51
Thanks for clarification. This is what I was asking about your comment "I guess so but it can detect correctly in ui theme auto !?"

Like I said it works correctly for me in Windows. I don't know why the bug appeared and judging by the code it seems impossible, but I'll try to guess something.

**Comment by tophf** [comment] 2023-09-26 14:02
I don't see anything in that change related to theme detection.

**Comment by cyfung1031** [comment] 2023-09-26 14:20
> I don't see anything in that change related to theme detection.

actually the text color of editor in system light is also different before and after that commit.

<img width="969" alt="Screen Shot 2023-09-26 at 23 19 32" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/11bb7cb6-ca9b-41a9-bc99-3bf3704fda21">

**Comment by tophf** [comment] 2023-09-26 14:24
There's nothing in that commit that changes anything in the editor. The color is the same gray here.

**Comment by cyfung1031** [comment] 2023-09-26 14:27
@tophf 
looks like it is due to the change in css rules ordering due to that commit

<img width="321" alt="Screen Shot 2023-09-26 at 23 25 03" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/6a8a7259-775e-4c2e-ad41-0992f064f8e8">

<img width="329" alt="Screen Shot 2023-09-26 at 23 25 19" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/2337d51b-20f6-489a-89ac-f8f195148d43">

<img width="684" alt="Screen Shot 2023-09-26 at 23 26 24" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/4acdf3fe-44dc-446c-8042-e11b24638d10">

**Comment by tophf** [comment] 2023-09-26 14:29
Thanks, awesome find, that explains it. The order may change during build, now I know where to look so I'll find it.

**Closed** 2023-09-26 14:31 UTC
Labels: bug

**Comment by tophf** [comment] 2023-09-26 14:33
Wow, another helpful find. So the culprit was our build's treating of `<style>` inside `setting-text.vue`.

**Comment by cyfung1031** [comment] 2023-09-26 14:36
> Wow, another helpful find. So the culprit was our build's treating of `<style>` inside `setting-text.vue`.

not working as per https://github.com/violentmonkey/violentmonkey/actions/runs/6314224669

don't consider to use the common approach `html[dark]` (most websites do like this) ?
e.g.
```css 
.... {
background: white;
}
[dark] .... {
background: black;
}
```

because now it relies on css rule ordering only

**Comment by tophf** [comment] 2023-09-26 14:38
That commit you've linked fixes the report bug (the locking of the script). The theme problem is fixed in 2939499b.

**Comment by cyfung1031** [comment] 2023-09-26 14:41
great!

**Comment by cyfung1031** [comment] 2023-09-26 14:45
@tophf now the problem becomes i can copy script B to script A and save without issues lol

although I think it is still okay if you intend to make like this.

<img width="1312" alt="Screen Shot 2023-09-26 at 23 43 54" src="https://github.com/violentmonkey/violentmonkey/assets/44498510/52bcb86a-f824-42e9-85c7-6d488c273392">

**Comment by tophf** [comment] 2023-09-26 14:48
No, it's a mistake.

**Comment by tophf** [comment] 2023-09-26 14:51
I couldn't reproduce it here. I see the error and saving is impossible.

**Comment by cyfung1031** [comment] 2023-09-26 18:13
> I couldn't reproduce it here. I see the error and saving is impossible.

request to revert https://github.com/violentmonkey/violentmonkey/commit/1a16fbc721e625910ac828d4c4a1c19ae81647c6

when installing the same script with the same url, it cannot detect there is an installed version, and it just add as a new script.

**Comment by tophf** [comment] 2023-09-26 18:51
Canno reproduce. It works correctly here.

**Comment by tophf** [comment] 2023-09-26 19:22
I've fixed one mistake in code, even though I couldn't reproduce the problem.

**Comment by cyfung1031** [comment] 2023-09-26 19:27
> I've fixed one mistake in code, even though I couldn't reproduce the problem.

It is working as normal.

It seems the bug is completely fixed. Thanks.
