### ISSUE TITLE
[BUG] GM_download not working in Firefox

### ISSUE THREAD

**Issue by sn260591** [violentmonkey/violentmonkey#2212] opened 2024-10-23 15:42 UTC
### Sequence of actions:
1. Install this script
```// ==UserScript==
// @name GM_download test
// @match https://example.com/*
// @grant GM_download
// ==/UserScript==

GM_download("https://example.com", "GM_download test");
```
2. Open https://example.com

### Problem:
The script does nothing.

### Expected result:
A file save dialog box appears.

#### Devtools console contents:
No errors.

#### Environment:
- OS: Windows 10
- Browser: Firefox 131.0.3
- Violentmonkey Version: 2.26.0

**Comment by tophf** [comment] 2024-10-23 15:44
Should be already [fixed in beta](https://github.com/violentmonkey/violentmonkey/releases/). Could you verify it? I'll publish a new stable release today if it indeed works.

**Comment by tophf** [comment] 2024-10-23 16:30
Actually, I can't reproduce the problem in 2.26.0, your code works for me.

**Closed** 2024-10-23 16:31 UTC
Labels: bug

**Comment by sn260591** [comment] 2024-10-24 12:55
I found that the problem occurs when changing the `What should Firefox do with other files?` setting to `Ask whether to open or save files`.

**Comment by tophf** [comment] 2024-10-24 12:57
Great find! I wonder if it's a bug in Firefox, because it doesn't even show neither a notification nor a message in devtools console.

**Comment by tophf** [comment] 2024-10-24 13:05
Indeed, it's a bug, there's an error in the browser toolbox console:

```
TypeError: this.mDialog is null[HelperAppDlg.sys.mjs:185:5](resource://gre/modules/HelperAppDlg.sys.mjs)
    reallyShow resource://gre/modules/HelperAppDlg.sys.mjs:185
    notify resource://gre/modules/HelperAppDlg.sys.mjs:611
```

**Comment by sn260591** [comment] 2025-07-20 09:09
How about adding `GM_info.downloadMode` option to switch to `browser.downloads.download()` like tampermonkey? Code `browser.downloads.download({ url: "https://example.com", filename: "download test" })` works properly.
