### ISSUE TITLE
Popup UI when in drop down list

### ISSUE THREAD

**Issue by waqas** [violentmonkey/violentmonkey#239] opened 2017-10-13 06:41 UTC
Right-click toolbar -> Customise... drop it in list.
Popup UI is not showing all...
![ ](https://user-images.githubusercontent.com/407/31533364-42e4c4e2-b00b-11e7-8fdf-c299cc94cb36.png)

**Comment by gera2ld** [comment] 2017-10-13 08:18
This seems to be a browser issue, possibly duplicate of #215 .
Please fill the issue template with essential info.

**Closed by gera2ld** 2017-10-13 08:18 UTC
