### ISSUE TITLE
GM_xmlhttpRequest does not work in synchronous mode

### ISSUE THREAD

**Issue by soviet-man** [violentmonkey/violentmonkey#349] opened 2018-02-13 21:52 UTC
It works in asynchronous mode only which is by default.
[GM wiki](https://wiki.greasespot.net/GM.xmlHttpRequest) says I can run this function in sync mode to obtain response right to the variable like this

```
var response = GM.xmlHttpRequest({
  method: "GET",
  url: "http://www.example.com/",
  synchronous: true,
});
```
Why cant I use sync mode in VM?

**Second**. Why your method is called **GM_xmlhttpRequest**, when GM's one is **GM.xmlHttpRequest**? (with 'Http' starts with capital letter as it should if we use camelCase)

**Third**. Why not making aliases for GM's functions like this
**GM.method** --> **GM_method**

**Comment by gera2ld** [comment] 2018-02-14 03:11
duplicate of #329

**Closed by gera2ld** 2018-02-14 03:11 UTC

**Comment by gera2ld** [comment] 2018-02-14 03:14
GM.* is implemented since Greasemonkey v4, which is still beta version, AFAIK.
GM_xmlhttpRequest is just named so in Greasemonkey v3, but renamed to GM.xmlHttpRequest since Greasemonkey v4.
GM.* and GM_* are implemented in different ways, they will be supported in the future but not yet.

**Comment by soviet-man** [comment] 2018-02-14 11:46
What about synchronous mode?
