### ISSUE TITLE
Can't sync with Synology WebDav

### ISSUE THREAD

**Issue by lonelygoneby** [violentmonkey/violentmonkey#1026] opened 2020-07-25 12:54 UTC
### How to reproduce it?
1.
2.
3.

### Environment
- Browser:
- Browser version:
- Violentmonkey version:
- OS:

**Comment by tophf** [comment] 2020-07-25 12:57
Can't reproduce, should fixed in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases).

**Closed by tophf** 2020-07-25 12:57 UTC
