### ISSUE TITLE
Examine @resource files

### ISSUE THREAD

**Issue by JonnyTech** [violentmonkey/violentmonkey#1041] opened 2020-08-12 01:27 UTC
### What is the problem?

Script does not seem to be updating `@resource` files after the userscript author has updated them in his GitHub repo. Issue raised there at https://github.com/Technical-13/MunzeeMap-Filter/issues/44

Unable to find a way in violentmonkey to check whether the `@resource` files have been loaded correctly.

### How to reproduce it?
1. Install userscript from: https://raw.githubusercontent.com/Technical-13/MunzeeMap-Filter/master/MunzeeMap-Filter.js
2. Browse to https://www.munzee.com/map/
3. Enable the `Show reporting` option with the script-drawn button
4. Move the map until an unknown element is found
5. A dialog pops up with details on reporting the new element
6. Check to see if the element has already been added at https://github.com/Technical-13/MunzeeMap-Filter/issues?q=is%3Aissue

### What is the expected result?

No dialogs to be shown because updated elements should be loaded in `@resource files`

### What is the actual result?

Script produces dialog for user to report unknown elements

### Environment
- Browser: Firefox
- Browser version: 79.0 64 bit
- Violentmonkey version:v2.12.7
- OS: Debian Linux 10 Buster

**Comment by tophf** [comment] 2020-08-12 03:35
This looks like a duplicate of #869 (UI part) and #879 (update part), the latter should be already implemented in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases), please test it.

**Closed** 2020-08-17 04:47 UTC
