### ISSUE TITLE
@match filter is case-sensitive!

### ISSUE THREAD

**Issue by jaydadhania08** [violentmonkey/violentmonkey#1044] opened 2020-08-17 03:20 UTC
### What is the problem?
`@match` filter is case-sensitive!

### How to reproduce it?
1. Create and install a userscript with `// @match    https://example.com/ABCD`
2. Visit https://example.com/ABCD   -> script is loaded as expected.
3. Visit https://example.com/abcd    -> script is **not loaded**!

### What is the expected result?
Visiting https://example.com/abcd should also load the script.

### What is the actual result?
Visiting https://example.com/abcd does not load the script.

### Environment
- Browser: Brave
- Browser version: Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)
- Violentmonkey version: v2.12.7
- OS: Windows 10 Home (64 Bit)

I don't know much about extensions development, so not sure how hard / easy it is to make the `@match` case-insensitive. But if that's not possible, we can have an extra directive such as `// @matchCaseSensitive false` to indicate that `@match` should ignore the case while matching URL.

I also know that I can use `@include` instead with a regex like `// @include    /https:\/\/example\.com\/[aA][bB][cC][dD]/`, but this looks like a pretty ugly hack, and I also read somewhere that `@match` performs better than `@include`.

This is my first post on GitHub so pardon me if I broke any rules / conventions.

**Comment by tophf** [comment] 2020-08-17 04:45
1. Chrome/Firefox `matches` mechanism of extensions follows the URL specification: 
  * the domain part is case-**insensitive**
  * the path part is case-sensitive
2. Chrome/Firefox `include_globs` mechanism of extensions is entirely case-sensitive. That's because it's so flexible that `*` can match across URL components i.e. both domain and path.

3. Greasemonkey4 is case-**insensitive** apparently everywhere (both domain and path parts of a match), which means they have a bug and don't follow their documentation that says `@match` is implemented the Chrome's way, it also [says](https://wiki.greasespot.net/Metadata_Block#.40include) a RegExp `@include /foo/` is always case-**insensitive**, which implies that a normal `@include` is case-sensitive (like it should be if it follows Chrome/Firefox `include_globs`) but it's not in GM4.

4. Tampermonkey and Violentmonkey are case-sensitive everywhere.

I guess it's pretty obvious that ideally we should follow Chrome/Firefox:
* `@match` domain is case-**insensitive**, path is case-sensitive (in VM also `@exclude-match`)
* `@include`/`@exclude` are case-sensitive 
* RegExp `@include`/`@exclude` are case-**insensitive** 

I just wonder about compatibility with the old scripts... @gera2ld ?

P.S. Someone should open an issue on Greasemonkey and Tampermonkey too per the above but I'm kinda lazy...

**Comment by tophf** [comment] 2020-08-17 04:51
Regarding the OP's proposal for `@matchCaseSensitive`, we will add it only if other userscript engines would add it, otherwise please use a regexp - in Violentmonkey everything is checked using regexp so *usually* there's no performance difference (we use caching a lot anyway).

**Comment by gera2ld** [comment] 2020-08-17 10:23
URLs should be case sensitive, according to W3's [HTML and URLs](https://www.w3.org/TR/WD-html40-970708/htmlweb.html).
I don't see why this is a bug. It works this way in Violentmonkey since the beginning.

I prefer case-insensitive RegExps (`/.../i`) in `@include`s (not sure if supported) to the `// @matchCaseSensitive false` proposal.
In this case maybe it's better to use RegExps instead since `@match` respects URL structures by design while `@include` just regards URLs as normal strings and test them with RegExps.

**Comment by tophf** [comment] 2020-08-17 13:54
> URLs should be case sensitive, according to W3's HTML and URLs.
The domain part of a URL is case-**insensitive** in all browsers and anywhere in the internet, also in extension's `match` mechanism which is the base of userscript's match.

**Comment by tophf** [comment] 2020-08-17 16:45
Hence my point that every userscript engine implements `@match` incorrectly. For example, our [hostMatcher](https://github.com/violentmonkey/violentmonkey/blob/15ed748db2231c60bb46d7f0ebfb56baea3047fc/src/background/utils/tester.js#L132) function should use `i` in RegExp. Maybe something else will be needed as well, I haven't looked into it yet. This is why this issue is marked as a bug. Also our regexp include doesn't match Greasemonkey4/Tampermonkey.

**Comment by jaydadhania08** [comment] 2020-08-17 19:31
> otherwise please use a regexp - in Violentmonkey everything is checked using regexp so _usually_ there's no performance difference (we use caching a lot anyway)

Performance is not a concern for me, but `@include` does not support RegEx switches such as `i`.
So something like `// @include /https:\/\/example\.com\/abcd/i` does not work at all.
I have to convert it into an ugly pattern like this:
`// @include /https:\/\/example\.com\/[aA][bB][cC][dD]/`.

If there is a way to use regex `i` switch here, I am very ready to use it.

**Comment by tophf** [comment] 2020-08-18 03:39
@jaydadhania08, in the next version the regexp include will be case-insensitive, see my first comment for more info.

**Closed** 2020-08-31 11:58 UTC
Labels: bug
