### ISSUE TITLE
[BUG] GM.xmlHttpRequest works in 2.13.0 but fails in 2.13.1+

### ISSUE THREAD

**Issue by paxunix** [violentmonkey/violentmonkey#1585] opened 2022-09-24 04:38 UTC
**Describe the bug**

Something has broken for GM.xmlHttpRequest from 2.13 to 2.13.1.  It doesn't break in all cases, but when it does break in some case, it breaks all the time in that case.

**To Reproduce**
1. Add a new user script:
```
// ==UserScript==
// @name            Testing weird stuff
// @description     Testing what happened that GM.xmlHttpRequest doesn't work right
// @include         https://*
// @version         1
// @grant           GM.xmlHttpRequest
// ==/UserScript==

function fetcher(opts)
{
    return new Promise((res, rej) => {
        opts.method = opts.method ?? "GET";
        opts.onload = response => console.log("opts:", opts, "response:", response);
        opts.onerror = response => rej();

        return GM.xmlHttpRequest(opts);
    });
}

function someFunc()
{
    let url = new URL("https://www.example.com");
    return fetcher({ url: url }).then(response => {
        console.log("response:", response);
    });

}

someFunc();
```
2. Go to https://www.example.com/
3. Verify the user script did run and execute.
4. Check the JS console and see the below error.

**Expected behavior**
1. No errors in the console.
2. console log showing the options and response object after the GET request succeeds.  The response should be a 200 and the responseText the content of https://www.example.com.

**Actual behavior**
Console shows:

`Uncaught TypeError: Cannot read properties of null (reading 'node')`

with stack trace:
```
VM300 injected.js:1 Uncaught TypeError: Cannot read properties of null (reading 'node')
    at VM300 injected.js:1:4687
    at pt (VM300 injected.js:1:10451)
    at mt (VM300 injected.js:1:10925)
(anonymous) @ VM300 injected.js:1
pt @ VM300 injected.js:1
mt @ VM300 injected.js:1
await in mt (async)
ft @ VM300 injected.js:1
ut @ VM300 injected.js:1
await in ut (async)
(anonymous) @ VM300 injected.js:1
await in (anonymous) (async)
(anonymous) @ VM300 injected.js:1
```

**What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?**
Verified it's broken on 2.13.1.2, broken on 2.13.1, and it works on 2.13.0.

**Environment:**
- OS: Ubuntu 22.04
- Browser: Chrome
- Browser Version: Version 106.0.5249.51 (Official Build) beta (64-bit)
- Violentmonkey Version:  broken on 2.13.1.2, broken on 2.13.1, and it works on 2.13.0

**Additional context**
I discovered this in a much more complex script that stopped working when my Violentmonkey extension updated to 2.13.1, but this was the smallest test case that I could make to illustrate the issue.

**Comment by gera2ld** [comment] 2022-09-24 05:39
Thanks for the detailed bug report.
This is a duplicate of #1578 and fixed in https://github.com/violentmonkey/violentmonkey/commit/6189e4a050260d7cf973a8cdb5d77df1c27be953.
It will be released soon.

**Closed by gera2ld** 2022-09-24 05:39 UTC
Labels: bug
