### ISSUE TITLE
Create script with same @name and @namespace caught unexpected error.

### ISSUE THREAD

**Issue by qrqhuang** [violentmonkey/violentmonkey#1075] opened 2020-10-02 15:10 UTC
### What is the problem?
I try to create a new script from exists one , and forget to modify the `@name` and `@namespace` medadata.
When save,  it prompts `Error: An unexpected error occurred`

### How to reproduce it?
1. create new script
2. copy exists script content to new
3. with no modify , then save.

### What is the expected result?
It should be friendly tips for name conflict.

### What is the actual result?
`Error: An unexpected error occurred`

**Comment by tophf** [comment] 2020-10-02 15:15
Please always specify the browser you're using as I couldn't reproduce in Chrome (our primary development browser). I see the bug in Firefox though.

**Comment by tophf** [comment] 2020-10-02 15:17
Actually, this is already fixed in the [upcoming version](https://github.com/violentmonkey/violentmonkey/releases).

**Closed by tophf** 2020-10-02 15:17 UTC
Labels: bug, firefox

**Comment by qrqhuang** [comment] 2020-10-02 15:23
@tophf sorry,  firefox which I use.
