### ISSUE TITLE
two scripts access the same variable using GM.getValue (on the page context)

### ISSUE THREAD

**Issue by roger21** [violentmonkey/violentmonkey#607] opened 2019-09-18 02:05 UTC
### What is the problem?

I have two scripts that use the same variable name to store data with GM.setValue/GM.getValue,
those two scripts overwrite eachother that variable.

GM.setValue/GM.getValue are built (into Promises) from GM_setValue/GM_getValue using a  gm4-polyfill.js like code.

the problem does not exist using only GM_setValue/GM_getValue (see the commented parts of the code)

the problem does not exist if i switch one or both scripts to "@inject-into content" (without changing anything else)

that problem does not exists with tampermonkey

### How to reproduce it?
1. install those two scripts https://paste.debian.net/plain/1101352 and https://paste.debian.net/plainh/9c871c46
2. open a webpage (with a clean console)
3. wait 5 seconds
4. read the log in the console

### What is the expected result?

the script "toto 2" that writes the log should write "toto 2 : value 2"

### What is the actual result?

"toto 2 : value 1"

also after some time the value set by the script "toto 1" appears in the "values" tab of the script "toto 2" which has never set that variable itself (that part seems to be limited to firefox though)

### Environment
- Browser: Chromium Version 78.0.3866.0 (Build officiel) (64 bits) and Firefox 69.0 64 bits
- Browser version: Version 78.0.3866.0 (Build officiel) (64 bits)  and 69.0 64 bits
- Violentmonkey version: 2.11.2
- OS: win 7 64 bits

**Comment by gera2ld** [comment] 2019-09-18 04:48
Problem confirmed and will be fixed in the next version.

The problem is caused by this line:
```js
GM = {};
```

By assigning a variable which has never been defined, the value will be attached to the global `window`, aka. `unsafeWindow` in this case.
Consequently a global `GM` is created in the first script, then the second script detects it and uses it. So `GM` in script 2 is actually created in script 1, calling `GM_getValue` and `GM_setValue` from script 1.

In Tampermonkey an official `GM` polyfill is provided, so this won't happen.

A workaround is to attach `GM` to `this`:
```js
this.GM = {};
```

All the other references of `GM` won't need to be changed since the script is executed in the scope of `this`.

**Comment by gera2ld** [comment] 2019-10-01 03:44
> the problem does not exist if i switch one or both scripts to "@inject-into content" (without changing anything else)

Just tested: if you switch both scripts to `@inject-into content`, the problem exists.

The problem is not about `@inject-into`, it exists as long as the two scripts run in the same context. So I don't understand what you insisted in #609.

**Comment by tophf** [comment] 2019-10-27 18:03
The next Violentmonkey will provide `GM` alias for Greasemonkey4 API.

**Comment by gera2ld** [comment] 2019-11-08 04:47
fixed in v2.12.1

**Closed by gera2ld** 2019-11-08 04:47 UTC
Labels: bug
