### ISSUE TITLE
Local scripts don't autoupdate on Firefox

### ISSUE THREAD

**Issue by leewdch** [violentmonkey/violentmonkey#460] opened 2018-10-14 14:56 UTC
### What is the problem?
I can't edit my scripts locally when using Firefox. I know I'm supposed to use an http server for the job and I thought I could use my already running apache http server but nothing is happening. Violentmonkey isn't complaining about errors and the path where it is loading my userscripts from is http://localhost/userscripts/myscript.user.js
Apache is set to follow symlinks and the userscripts folder isn't in my apache root path. Just wanted to mention this custom setting I have.

### How to reproduce it?
1. Start an apache http server
2. Symlink a folder from a different location
3. Open and install the userscript as usual enabling local checks in the options

### What is the expected result?
Autoupdates

### What is the actual result?
No changes at all

### Environment
- Browser: Firefox
- Browser version: ESR 60.2.2
- Violentmonkey version: 2.9.7
- OS: Linux

**Comment by leewdch** [comment] 2018-10-14 15:00
I just tried to make a userscript in my apache root directory and it correctly autoupdated. Guess it doesn't work well with symlinks. I also forgot to mention that the symlink goes into an ntfs partition

**Comment by leewdch** [comment] 2018-10-14 15:03
I cloned my repository containing userscripts directly into my apache root path but again it fails to update the scripts. Maybe it fails to check scripts from subdirectories and it checks for updates only in the root path (?)

**Comment by leewdch** [comment] 2018-10-14 15:10
I noticed that it also fails to check for changes if I remove the script completely and reinstall it from scratch. It jeeps showing me that old script seven if I manually changed it

**Comment by leewdch** [comment] 2018-10-14 19:12
I made a new virtualhost and moved my scripts in the root of the new directory on a totally new port. This time I'm hosting it on port 8000 and I changed ownership to http:users. This time the file autoupdates normally. I don't know if this is an issue with subfolders or an issue with ownerships or both. I'll try installing a dummy script in my subfolder on :80 and testing with different ownership sets

**Comment by leewdch** [comment] 2018-10-15 01:37
After some time violentmonkey started to not update the scripts again. This time I thought it could be a problem with apache caching files so I disabled cache for my virtualhost and tried doing changes into the files and I noticed changed were correctly displayed as the "Last modified" value changed as well. I really don't know why it's refusing to load my updated script. Removing the script and installing it from scratch still shows the old script somehow

**Comment by gera2ld** [comment] 2018-10-15 02:13
> Removing the script and installing it from scratch still shows the old script somehow

This indicates that the script is cached by your server. Violentmonkey just sends a request for the file to see if anything has changed, i.e. it works the same no matter what kind of path the file has.

Perhaps you can see what the server returns in the developer tools.

**Comment by leewdch** [comment] 2018-10-15 14:43
I guess you are right. I just tried disabling violentmonkey and loading the same userscript and even if the last modified line is updated showing I edited the file it still shows the old file. I thought I disabled cache but looks like this isn't working. (this is just an example image to show you what I'm talking about)
![image](https://user-images.githubusercontent.com/11262717/46958044-360a0480-d099-11e8-9461-dfab0ab4b962.png)

**Comment by T1mL3arn** [comment] 2018-10-17 05:13
Stuck with the same problem. I use `py -m http.server`, not Apache. And Firefox browser.  I noticed that if a local script doesn't get any updates for a while, then frequency of VM requests is significantly decreases. Then it is needed to wait several minutes after a local update (sometimes about 10-15) to get an update in VM's editor.

**I solve this problem by cleaning browser's cache!**

Wonder if this can be solved on VM's side or this is just browser-related.

**Comment by pmorch** [comment] 2018-10-30 14:59
I've noticed this too. The recommendation from [How to edit scripts with your favorite editor? - Violentmonkey](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/#install-a-local-script) is to use `python3 -m http.server`.

But I then discovered that I got hit by the [default firefox caching](https://www-archive.mozilla.org/projects/netlib/http/http-caching-faq.html). _Unless HTTP headers to the contrary_, the older the file is, the more seldom Firefox will actually query the server for the URL.

So a good start would be to touch the file in question just before you open it in Violentmonkey the first time. Then it'll keep querying it periodically. Touch it once in a while if the interval becomes too long.

But instead of using `python3 -m http.server` I use node/npm's [indexzero/http-server: a simple zero-configuration command-line http server](https://github.com/indexzero/http-server#readme). Using that and it's `-c-1` option to disable caching entirely, Firefox now requests the URL every second or two like clockwork.

I recommend mentioning that in [How to edit scripts with your favorite editor? - Violentmonkey](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/#install-a-local-script). But now you guys know at least.

**Comment by gera2ld** [comment] 2018-11-01 08:50
Thanks to @pmorch and @T1mL3arn , the problem seems to be solved. [Document](https://violentmonkey.github.io/2017/03/14/How-to-edit-scripts-with-your-favorite-editor/#install-a-local-script) has been updated.
So closing.

**Closed by gera2ld** 2018-11-01 08:50 UTC

**Comment by T1mL3arn** [comment] 2019-09-07 13:56
Since there are some troubles with node's `http-server` (see https://github.com/http-party/http-server/issues/556 , https://github.com/http-party/http-server/issues/525 , https://github.com/http-party/http-server/pull/541 ) it is not possible to use it out-of-box until its issues will be resolved.

But I discovered the previous python-way can be used without caching problem. The command `py -m http.server --cgi` does the trick. According to [python's doc](https://docs.python.org/3/library/http.server.html#http.server.CGIHTTPRequestHandler) cgi-mode forces status code `200`, so there won't be `304` code as it is without cgi-mode.

**Comment by WiliTest** [comment] 2022-07-18 10:33
We are 2 people with 2 PC, we followed the the drag-drop technic from the [tuto](https://violentmonkey.github.io/posts/how-to-edit-scripts-with-your-favorite-editor/#known-issues) to edit it with VScode (we use Edge/chromium browser). It did not work: the changes made in VScode are not showing on edge/violentmonkey.

**Comment by tophf** [comment] 2022-07-18 11:47
Apparently they didn't enable file access on chrome://extensions page for Violentmonkey. The tutorial shows UI for old Chrome, but in new Chrome the option is shown after clicking the `Details` button on chrome://extensions page. Alternatively they can use a local web server as shown in the tutorial.

**Comment by WiliTest** [comment] 2022-07-25 16:07
> Apparently they didn't enable file access
If you are talking about us, we did it:
![Dimmer_2022-07-25_18-07-01](https://user-images.githubusercontent.com/24194840/180824381-00357d96-acfa-4abf-94bb-844f8ddbad8e.png)

**Comment by tophf** [comment] 2022-07-25 16:15
I guess you need to enable autosave in VSCode.

**Comment by WiliTest** [comment] 2022-07-25 17:10
> you need to enable autosave in VSCode.
I did it, but it still doesn't work. 

Precisely it only works during the confirm installation (the change made in VS code show in the VM script tab of the browser, but when I click on `confirm` and then open the script on VM, it doesn't sync anymore).

**Comment by tophf** [comment] 2022-07-25 17:34
I guess it's a bug in the old stable version of Violentmonkey, which is fixed in [beta](https://github.com/violentmonkey/violentmonkey/releases).

**Comment by Gettyk** [comment] 2023-02-13 17:54
I also can't make it work with vscode. 
I dragged my file ".user.js" into the browser and confirmed the installation ('track local file..." is checked). 
Then I closed the tab, modified my local file, saved it, opened violenmonkey and then opened my script and it isn't modified. 
 I installed the latest beta version "Violentmonkey-beta-webext-v2.13.9.3" and I have auto-save enable.
I have also enabled "Allow access to file URLs" on chrome://extensions for the beta.

**Comment by Gettyk** [comment] 2023-02-13 18:35
That's right, it's working when the installer tab is open (and after clicking on installing). Thanks a lot for making it work but it's not very practical as each time I restart working on the script, I need to redo the install. It's a nice feature but it would be great to have a permanent editable script.

**Comment by 4tg0x** [comment] 2023-07-01 20:42
when i drag the script onto chrome, it simply downloads it instead of confirmation install window?
yes i add enable `allow access to file urls` 
please help.
