### ISSUE TITLE
ViolentMonkey Broken in v2.7.0

### ISSUE THREAD

**Issue by uBlock-user** [violentmonkey/violentmonkey#144] opened 2017-06-20 14:24 UTC
- Script cannot be disabled when installed via URL

- Scripts CANNOT be installed via a direct link 

For example 
- > Browse to https://jspenguin2017.github.io/uBlockProtector/ 
->  Click on Jump on installation instructions buttons 
->  Do what Step 4 says

- Can't set script order manually, broken again! 

What is going on ? With v2.7.0 it looks like VM is completely broken !

**Comment by gera2ld** [comment] 2017-06-20 14:38
The script does not have a `@namespace`, and is regarded as an invalid script.

**Comment by gera2ld** [comment] 2017-06-20 14:47
I think I will make `@namespace` optional.
Script order works here, can you provide more details?

**Comment by gera2ld** [comment] 2017-06-20 15:07
Cannot reproduce this:
> Script cannot be disabled when installed via URL

**Comment by uBlock-user** [comment] 2017-06-20 15:25
> The script does not have a @namespace, and is regarded as an invalid script.

It never had namespace and it always worked and it used to work with v2.6.4, now it doesn't.

> Script order works here, can you provide more details?

Try putting the script on the top manually by picking it up with the mouse and dropping it at the top position and then refresh the dashboard page, it will back at the bottom.

> Cannot reproduce this:

Script cannot be disabled when installed via URL

Open dashboard, then click on Install from URL, put this URL - https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtector.user.js and click OK, script installation page will appear, confirm installation and close, now back on dashboard Click on Disable and nothing happens.

**Comment by uBlock-user** [comment] 2017-06-20 15:27
All of this started happening with v2.7.0 and didn't happen before, so the script is not invalid in any way.

**Comment by uBlock-user** [comment] 2017-06-20 15:33
Wow, check for updates button is also not working for this script when installed from URL. Wtf ?

**Comment by uBlock-user** [comment] 2017-06-20 15:42
Regarding Script order, I can reproduce it 

https://i.gyazo.com/dafa28c7f104e6dc3beefde901c54a10.mp4

**Comment by uBlock-user** [comment] 2017-06-20 15:45
Check for Updates button doesn't work for uBlock Protector Script for some reason today, it used to work untill yesterday - https://i.gyazo.com/1c4136c205ab5b8f610750ba76db5afd.mp4

**Comment by uBlock-user** [comment] 2017-06-20 15:48
Also for some reason I cannot disable uBlock Protector Script ! Why is that ?

https://i.gyazo.com/96ee9c9e01b09ad575544b2c3ff8b8ac.mp4

**Comment by uBlock-user** [comment] 2017-06-20 15:54
Okay, even after adding //@namespace, it's not working

https://i.gyazo.com/398759c39abee4c20fb3723dd0d9f092.mp4

**Comment by gera2ld** [comment] 2017-06-20 17:37
`@namespace` is misspelled in the last video. Anyway, it's a bug to keep reloading and fixed in the related commit.

> - cannot disable uBlock Protector Script
> - script order

happen to this script only, whether installed by URL or click.
The reason is lack of script ID (just this script).
It seems to be a Chrome issue and appears in v2.6.4 too, so not a regression.
I will look into this further.

**Comment by uBlock-user** [comment] 2017-06-20 17:48
> happen to this script only, whether installed by URL or click.
The reason is lack of script ID (just this script), which means everything done with this script will fail.
It seems to be a Chrome issue and appears in v2.6.4 too, so not a regression.

Gee, now that makes sense. Thanks for the info.

**Comment by jspenguin2017** [comment] 2017-06-20 18:49
> The reason is lack of script ID

What ID? Do you have some doc on this?

**Comment by gera2ld** [comment] 2017-06-20 19:03
@jspenguin2017 It's not about the script itself.
ID here is the primary key of each script (indexeddb record) used by Violentmonkey internally.
On earlier versions of Chrome, the primary key should be returned with script contents.
But on the latest Chrome, after testing for a while, I found that the primary key is missing when querying large scripts. I have tested several scripts, by truncating the code of a large script, the primary key came back.
A workaround is to add the primary key to returned object manually after query.

**Closed** 2017-06-20 19:05 UTC

**Comment by uBlock-user** [comment] 2017-06-20 21:32
So the issue is the with the Chrome or with VM ?

**Comment by gera2ld** [comment] 2017-06-21 02:01
I think it's with Chrome. VM has not changed its DB for a while.

**Comment by gera2ld** [comment] 2017-06-21 02:21
- works on Chrome 59.0.3071.109
- not work on Chrome 61.0.3136.0
Reproduced by <https://gist.github.com/gera2ld/29addf3f45fb483622cad2b205208e0b>
So it is a Chrome issue.

**Comment by jspenguin2017** [comment] 2017-06-21 02:26
@gera2ld So... Are you filing a Chromium bug? 

Chrome 61 is still on dev channel, right? It might be fixed when it hit stable.

**Comment by gera2ld** [comment] 2017-06-21 02:37
Just filed a bug: <https://bugs.chromium.org/p/chromium/issues/detail?id=735317>

**Comment by jspenguin2017** [comment] 2017-06-23 23:52
Looks like Chromium team fixed it. 👍 👍 👍
