### ISSUE TITLE
[Feature] Can an option be added to adapt the window length automatically?

### ISSUE THREAD

**Issue by freedomspiritJohn** [violentmonkey/violentmonkey#1882] opened 2023-09-03 04:38 UTC
Sometimes the scripts and options for webpage loading are particularly long, making it impossible to display all the lists in their entirety. However, there are two scroll bars available, so I hope that the window can be extended to fully display all the scripts and their corresponding option lists at once.
![GIF 2023-9-3 12-32-06](https://github.com/violentmonkey/violentmonkey/assets/129288685/985c4838-e297-4e4e-a954-5f7f16d15400)

**Comment by tophf** [comment] 2023-09-03 04:50
Normally it already happens automatically, so in your case it's a bug, apparently caused by incorrect calculation of available height in our code. What is your display resolution?

**Comment by freedomspiritJohn** [comment] 2023-09-03 05:17
> Normally it already happens automatically, so in your case it's a bug, apparently caused by incorrect calculation of available height in our code. What is your display resolution?

computer display resolution ：
![image](https://github.com/violentmonkey/violentmonkey/assets/129288685/d10ae3f9-7ee9-46f5-abea-527ea9d9d540)
browser display resolution：
![image](https://github.com/violentmonkey/violentmonkey/assets/129288685/e9e46c23-ee4a-4043-ba03-777bb01fee7d)

**Comment by freedomspiritJohn** [comment] 2023-09-03 05:21
> > Normally it already happens automatically, so in your case it's a bug, apparently caused by incorrect calculation of available height in our code. What is your display resolution?
> 
> computer display resolution ： ![image](https://user-images.githubusercontent.com/129288685/265243411-d10ae3f9-7ee9-46f5-abea-527ea9d9d540.png) browser display resolution： ![image](https://user-images.githubusercontent.com/129288685/265243510-e9e46c23-ee4a-4043-ba03-777bb01fee7d.png)

When I change the browser page zoom  to 100%, it will look like this：
![image](https://github.com/violentmonkey/violentmonkey/assets/129288685/e92cf179-3e61-4579-a907-b6b5ed0cc24d)

**Comment by tophf** [comment] 2023-09-03 05:47
Thanks for investigation! It'll be fixed in the next release.

**Closed** 2023-09-03 05:46 UTC
Labels: bug
