### ISSUE TITLE
[BUG] VM keep deleting userscripts randomly beyound 200

### ISSUE THREAD

**Issue by neoOpus** [violentmonkey/violentmonkey#2184] opened 2024-09-12 07:29 UTC
I’ve been trying to identify the issue with VM after importing userscripts from TM and discovered it randomly deletes scripts beyond 200. I’m unsure if this is a limitation or a bug, but it’s frustrating, especially since I have around 800 (yeah, I am superpoweruser). I attempted to restore them individually after mistakenly believing I had made an error in updating to find that the work I did has been reversed and I wasted few hours trying to cleanup, organize and verify that has been wasted. 

However, VM clearly has limitations; as it doesn’t update more than 20 userscripts and it keep showing a stupid popup for every attempt to update one manually that cannot be disabled, and unlike TamperMonkey, it lacks the option to select multiple scripts for batch operations. While I initially preferred the faster and slightly improved UI that is close to Stylish.

I regret switching, as it lacks many features and controls available in TM and these are the kind bugs that I cannot tolerate!

I tried to switch to ScriptCat but it is still not there too, its UI is mainly in Chinese and it lacks a lot of features too. Switching back to TM even if it is slower and has its own set of problems :(

HUGE DISAPOINTEMENT

**Comment by tophf** [comment] 2024-09-12 10:52
> randomly deletes scripts beyond 200

There's no such limit, so it's a bug, probably in the import-from-TM function.

> VM clearly has limitations; as it doesn’t update more than 20 userscripts

No such limit, so it's a bug that you are the first to report. I can't reproduce it though.

> it keep showing a stupid popup for every attempt to update one manually that cannot be disabled

A screenshot please? The update notification can be disabled in the options, either globally or individually per each script.

**Comment by tophf** [comment] 2024-09-12 11:08
I've just tried 828 scripts and nothing gets deleted here. Scripts are updated normally except greasyfork which reports 503 error after a certain number of checks, so I'll add a delay for this site.

One known explanation for automatic removal of scripts is sync (#1260), in which case the scripts end up in the `Recycle bin` in VM dashboard. If you don't have it configured, maybe you can upload your exported backup from TM to me via email and I'll try debugging it?

**Comment by neoOpus** [comment] 2024-09-12 17:02
> I've just tried 828 scripts and nothing gets deleted here. Scripts are updated normally except greasyfork which reports 503 error after a certain number of checks, so I'll add a delay for this site.
> 
> One known explanation for automatic removal of scripts is sync (#1260), in which case the scripts end up in the `Recycle bin` in VM dashboard. If you don't have it configured, maybe you can upload your exported backup from TM to me via email and I'll try debugging it?

I configured OneDrive for sync and I've suspected it after my last attempt yesterday to get the scripts back to the main list from the recycle bin (a very annoying thing to do as I have to restore them one by one and many are duplicates) in order to export them and move... I will check again so I don't mislead anyone!

Do you think that there is a limit of number of files that are synched to OneDrive?

I will send you the file via email!

**Comment by neoOpus** [comment] 2024-09-13 22:38
I think you are right, I will give it another try but please add more features to ease the management like checkboxes that allow selecting multiple userscripts to do operation upon... also fix the bug of update (I tried after you wrote me and it is still there, only few get checked like 20 max), also add more sorting options and more columns for that like in TM... I have some other requests and suggestions, but I will come back later to look if some people did ask for them already or not otherwise I will and see how I can help make this evolve by being doing something myself.

Thank you again for your kind support.

**Comment by tophf** [comment] 2024-09-14 04:34
> checkboxes that allow selecting multiple userscripts to do operation upon

I've only used it once or twice over the few years I was using TM, so I'm not particularly keen on adding it. It'll be added only if someone (e.g. you) describes a convincing practical scenario for this feature.

> the bug of update

Assuming it's about scripts from greasyfork, it's fixed in 2.23.

> add more sorting options and more columns for that like in TM

Violentmonkey was built as a simpler/lighter version of TM, so it intentionally doesn't implement many features that unnecessarily overload the UI. Some features may be still added, but only if someone (e.g. you) describes a convincing practical scenario that happens more than once in a blue moon.

I'm closing this issue, because there is an existing issue for removal of scripts and the rest of the problems should be presented as separate issues with more details.

**Closed by tophf** 2024-09-14 04:34 UTC
Labels: bug, not reproducible

**Comment by neoOpus** [comment] 2024-09-14 06:48
> I've only used it once or twice over the few years I was using TM, so I'm not particularly keen on adding it. It'll be added only if someone (e.g. you) describes a convincing practical scenario for this feature.

Sure here are few scenarios, that I used for:

1. Exporting a set of extensions that are specific to a website like Github in order to aleviate the resource consumptions and using them in another profile that is just to browse Github for example or Youtube... Or by category (coding, entertainment, gaming, banking...) ! *this saves time instead of having to reinstalling them one by one by opening, copying the URL etc...
2. Deleting many userscripts at the same time.
3. Picking those that we want to update.
4. Select All or some, then do some operations (TM is great in this regard because it is possible to do it by clicking on top) But also it is possible to use keyboard keys to be more selective and accelerate the selection via (CTRL and specially SHIFT) both can be used together as well to skip some and select some more quickly starting from the focused checkbox or element without deselecting the previously selected ones ... very useful when paired with sorting by date, order, name, url, source, 
5. Can be great for applying tags (TM added them in the Beta version)

**Comment by tophf** [comment] 2024-09-14 06:54
> Exporting a set of extensions

Export everything then simply delete the unnecessary scripts from the zip file?

> Deleting many userscripts at the same time
> Picking those that we want to update

Clicking the delete/update icon directly is much quicker than clicking the select icon, then choosing the action.

> Select All or some, then do some operations

Which operations specifically?

> Can be great for applying tags

This is the only useful scenario I acknowledge so far, and I thought about it as well, however I don't use tags personally, so I'm not particularly motivated to implement it. Still makes sense though.

**Comment by neoOpus** [comment] 2024-09-14 16:55
Everything I mentioned is genuinely useful to me at least but I am sure that everyone will find them as useful once they are implanted! 

As they can be done quickly in order to isolate a problem or just manage the userscripts without extra operations, I was even to ask if it is possible to have a feature like what exists in this extension manager that allow to group the userscripts, or put those enabled into one... This can help saving those who have been enabled without having to remember which and which into a group then trying to isolate the one that is causing the issue with certain websites by toggling the entire group then picking... It can also help when we move to another machine and maybe sharing... 

Also, it has a search box that can help find quickly the extension... And it would be amazing to be able to assign a name to not rely on what the authors named them which can be in another language like Chinese to the userscripts (or extensions) and add a **note** (that remain even if it gets updated where we can just put what we have altered to reapply them later or just to **note** an issue with them... I was hoping that at some point we can have a **universal** manager that allow to manager userscripts, userstyles and Extensions from the same UI with ease... 

And finally I was aspiring to push for a unified design across most extensions and userscripts, creating a boilerplate that get adopted by the community to avoid differing UI styles and discrepancy between them or a plugin system that allow to pick just what we need to reduce conflicts between certain. Currently, as you already know for certain that each extension and userscript injects its own libraries alter the website that another also does as well and both have from what the extension and userscript offers to avoid overlapping or conflict, consuming resources and hindering navigation. I believe VM and Stylish have the foundations for this.

Ultimately having an AI-powered (no hype intended) Agent that works via API, Locally or WebNN on the background to analyse, optimize, group, rename, translate, fix etc... each of the extensions, userscripts (but that's another story) ... 

Sorry for the annoyance and sorry for myself for not being a software engineer myself that is capable of initiating and managing such project!

![image](https://github.com/user-attachments/assets/fa5e504e-993b-48d6-9ef5-6a9f7e15bdc0)
![{A4F64B78-11FD-4B1B-B284-6200F8199790}](https://github.com/user-attachments/assets/d8b17111-57e8-4003-a0a2-994db0e8c022)
