### ISSUE TITLE
Either startup or match-script-to-site sometimes fails at browser-on time

### ISSUE THREAD

**Issue by filbo** [violentmonkey/violentmonkey#73] opened 2016-11-11 11:14 UTC
I'm dealing with this as a bug of Social Fixer (socialfixer.com), an add-on for Facebook.

However, I've abstracted the problem down to a simple (if long) procedure involving Opera 43 or later, since it has nice control over tab startup behavior.  I've seen the problem with Opera versions 40..43 and VM 2.5.1, 2.5.2.  I believe it's a generic startup issue (and have demonstrated on Chrome), but Opera is particularly adept at demonstrating it, especially with the right version and settings:

1. Install opera-developer 43 (http://www.opera.com/computer/beta, Opera developer [Download now])

2. Run:
      $ opera-developer --user-data-dir=/tmp/startup-bug
   [or Windows equivalent, whatever that would be]

3. Configure these settings:

-   opera://settings =============> [x] Show advanced settings
-    opera://settings/?search=delay => [ ] (do not) Delay loading of background tabs
-    opera://flags/?search=reload-v => Only auto-reload visible tabs: DISABLED
-    opera://flags/?search=d-lazy ===> Extended lazy session loading: DISABLED

4. Install Violentmonkey:

   https://addons.opera.com/en/extensions/details/violent-monkey [Add to Opera]

5. Install test script:

   VM icon -> Manage scripts
   [New]
   (select all, erase)
   Paste in:

========================================

// ==UserScript==
// @name           Testing VM startup
// @namespace      http://blah.blah.blah
// @include        /^https?:\/\/*/
// @run-at         document-start
// @grant          GM_getValue
// @version        3.14159265358979323
// ==/UserScript==
document.body.style.background = "#880088";

========================================

   [Save & Close]

6. Open https://violentmonkey.github.io/nex/
   -- background should be purple

7. Close all other tabs, leaving only the purple github tab

8. Right-click on tab, "Clone tab"
    -- 2nd tab, background is purple

9. Clone 9 tabs this way
   -- session now consists of 9 purplized violentmonkey.github.io tabs

10. Close Opera

11. Reopen Opera:
      $ opera-developer --user-data-dir=/tmp/startup-bug

12. Look at all 9 tabs -- are all purple? (Note: ctrl-1 through ctrl-9 visit 9 tabs)

13. Goto 10, until satisfied

========================================

My results just now:

Restart#1: whi0 whi0 whi0 pur4 whi0 pur3 pur2 pur1 pur1
Restart#2: whi0 whi0 whi0 whi0 whi0 whi0 whi0 whi0 whi0 
Restart#3: whi0 whi0 whi0 whi0 pur1 pur4 pur3 pur2 pur5
Restart#4: whi0 whi0 whi0 whi0 pur1 whi0 whi0 whi0 whi0 
Restart#5: pur4 pur1 pur1 pur2 pur5 pur3 pur2 pur3 pur4
Restart#6: pur8 pur2 whi0 pur1 pur7 pur5 pur4 pur3 pur6

"whi0" means "white (userscript didn't start)" + "monkey has no number on his face"
"pur3" means "purple (userscript ran)" + "3 on monkey's face"

I think the number means "VM believes it has %d scripts associated with this site".  It should be identically equal to 1 in this test!

I've had runs (not recorded in this session) where all were "pur1" and everything looked perfect.

Here, restart#6 looks very much like each is receiving an event giving a tab number (in some abstract order, e.g. random/racy startup order, not visible tab order), and they're failing to convert that to a count (and so does restart#3, except the tabs that didn't start at all).  BUT, restart#5 doesn't look that way at all, as it has two-each of 2, 3 and 4.  restart#1 does fit the conjecture if I assume that at least one tab *did* manage to convert its event data to a 1-count.

========================================

Also tested with Chrome, but only version 49 (later won't install on my old Ubuntu):

Single-tab shows the problem.

Multi-tab shows the problem -- only in the tab which is visible at startup.  Other tabs load sequentially afterwards and all start correctly.  It *does* show weird numbers on the monkey's face.

**Comment by filbo** [comment] 2016-12-01 12:27
In fact, if I restart Opera while the Violentmonkey UI is visible, half the time _it_ doesn't start up right.  I don't know if it's the same root cause, but the parallel is striking.

Opera settings that might be relevant:

- Using opera-developer (currently 43.0.2420.0, will be 43.0.2423.0 next restart)
- opera://settings/?search=tab
[x] Delay loading of background tabs

- opera://flags/?search=tab
Background tab throttling [enabled]
Only auto-reload visible tabs [enabled]
Extended lazy session loading [disabled]
Lazy session loading enabled by default [enabled]
Session persistent tab activation order [enabled]

**Comment by gera2ld** [comment] 2017-02-10 15:40
I think this is the expected behavior.
It takes some time for Violentmonkey to start up and load all the scripts. So the tabs that are loaded immediately will not be injected by Violentmonkey.
A force reload might cause data loss. Maybe a manual refresh for such tab is acceptable?

**Comment by filbo** [comment] 2017-02-11 00:19
It's expected behavior that if the VM manager tab is the active tab at startup time, it never successfully initializes?

VM should be aware of whether its back end is fully initialized or not.  Tabs which start up before then should have a VM event listener waiting for VM backend to finish init, then get on with the business of injecting etc.

"Late injection" might seem dangerous -- well, clearly it might actually be dangerous in some cases, but by way of counterexample I'll point out that Firefox apparently _reinjects_ FF extensions when they're upgraded!  Which is some high-powered craziness.  I've seen where a tab has had an extension running for hours or days, then the extension's updated in FF's "store", FF downloads and auto-updates it, de-injects the old version and injects the new one into the already running tab.

If that hasn't caused their users to burst into flames, VM injecting scripts a few hundreds ms late during browser initial startup should be _sufficiently_ safe.

**Comment by gera2ld** [comment] 2017-02-11 01:29
VM manager tab initialization issue should be a bug.

A script injection is different from an extension injection.
Once a script is executed, there is no way to de-inject it but reloading the page. But if an extension does nothing to the document content, it can be reloaded safely without affecting the page.

So if VM is ready, it knows which tabs have not been injected since it's ready, but it's not safe to just reinject the scripts. In case of manually disabling and enabling VM, a force reinjection will cause the scripts being executed repeatedly. It's also not safe to force reload those tabs since there might be POST requests or unsaved user modifications.

**Comment by simonlindholm** [comment] 2017-11-07 20:44
> In case of manually disabling and enabling VM, a force reinjection will cause the scripts being executed repeatedly.

It seems like this problem at least could be dealt with by force-injecting only on the `runtime.onStartup` event (or listening for `runtime.onInstalled`, possibly).

(This happens to me in Firefox as well -- I need to hit F5 immediately after startup for user scripts to activate.)

**Comment by NudeSpoons** [comment] 2018-05-17 08:09
@gera2ld Is this still an outstanding issue for users of the Opera, Firefox (and possibly other) browsers?

**Comment by filbo** [comment] 2018-05-18 01:01
Still happening to me on opera-developer 55.0.2955.0 (current, based on Chromium 67.0.3396.18); with Violentmonkey 2.9.4.

**Comment by gera2ld** [comment] 2018-05-24 06:28
What about an option to reload pages on extension start?

**Comment by filbo** [comment] 2018-05-24 20:32
Given a choice of: (1) force-inject VM-supplied userscripts 'late', knowing that the affected tabs have been open for a while; or (2) force-reload such tabs, then inject the userscripts 'on time' --

I strongly choose (1).  Reload is extremely problematic!

From @simonlindholm's comment above, it seems like VM background script should know that the browser 'just' started.  Anyway surely there is an equivalent of `uptime` ?  So, you should reasonably be able to distinguish between 'I am late-injecting into a bunch of tabs because the browser just started and fired up those tabs from a saved session' vs. 'VM has just been disabled and re-enabled, but the browser has been up for minutes/hours/months'.

What to do in the latter case is still an open question which you might need to struggle with.  But is not the question here.  [[ Regarding that: would it be entirely out of the question for VM to modify the DOM of injected-into tabs?  Add a tag to the HTML tag, 'vm-injected' or whatever.  Then if user disables/re-enables VM, on scan of tabs you can tell which have already been injected.  Vs., well, suppose they have VM installed + a collection of scripts, but it was disabled on browser startup, and now it is hours later and they suddenly enabled VM.  In **that** case maybe VM should actually pop up a dialog about how it isn't going to inject into already-open tabs, user should reload tabs if that's what they want -- maybe with a 'force all tabs to reload' button for the foolhardy... ]]

Testing right now, on opera-developer 55.0.2962.0 and VM 2.9.4, I actually tried to follow my 13-step thing up above.  Almost every part was different (revised steps below, after narrative).

Behavior was also different, now more consistent: on every startup, every single tab failed to inject the script; and the Violentmonkey 'dashboard' tab came up empty.  I was able to 'fix' each tab by a manual reload.

So there is still the part that you acknowledged as an actual bug (VM dashboard doesn't start); and the part I say is also a bug (VM doesn't inject into tabs loaded from saved-session at browser startup).

Updated repro steps below:

======

1. Install opera-developer 55 (I got 55.0.2962.0): https://www.opera.com/computer/beta, Opera developer [Download now]

2. Run:
$ opera-developer --user-data-dir=/tmp/startup-bug
[or Windows equivalent, whatever that would be]

3. Configure this setting:

opera://settings/?search=delay => [ ] (do not) Delay loading of background tabs

4. Install Violentmonkey:

4a. Opera Install Chrome Extensions (I got 2.5.2): https://addons.opera.com/en/extensions/details/install-chrome-extensions
4b. Chrome Violentmonkey (I got 2.9.4): https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag

5. Install test script:

VM icon -> Open Dashboard
['+' -> New]
(select all, erase)
Paste in:

========================================

// ==UserScript==
// @name Testing VM startup
// @namespace http://blah.blah.blah
// @include /^https?://*/
// @run-at document-start
// @grant GM_getValue
// @Version 3.14159265358979323
// ==/UserScript==
document.body.style.background = "#880088";

========================================

[Save & Close]

6. Open https://github.com/does-not-exist
-- 404 page, background of lower part is purple

7. Close all other tabs, leaving only the purple github tab

8. Right-click on tab, "Duplicate tab"
-- 2nd tab, background is purple

9. Clone 9 tabs this way
-- session now consists of 9 purplized github.com 404 tabs
-- (I actually replaced the 9th tab with the Violentmonkey 'dashboard', so 8x github-404, 1x dashboard)

10. Close Opera

11. Reopen Opera:
$ opera-developer --user-data-dir=/tmp/startup-bug

12. Look at all 9 tabs -- are all purple? (Note: ctrl-1 through ctrl-9 visit 9 tabs)

13. Goto 10, until satisfied

**Comment by filbo** [comment] 2018-05-24 20:38
This is an ongoing user-reported 'bug' in Social Fixer (SFx).  Of course they are mostly not using VM; most are using the web-extension packaged version of SFx, some are using TM or VM, a few may still be using GM + an old version or fork of FF (we don't work on GM4 yet, which seems to have jumped the shark anyway).  At some level there is a _browser_ bug in which it mis-initializes extensions at session load time (probably a timing issue).  And seems to happen across multiple browsers & engines.  So in part I am hoping to learn from your much deeper knowledge, learn what you end up using to properly detect the _right_ time for VM to start operating, and possibly use the same event handling in our extension code.  As well as benefit from it by proxy, when we're running as a userscript under VM.

**Comment by gera2ld** [comment] 2018-05-25 01:30
Scripts are supposed to work at the time of `@run-at`, which leads to different kinds of initiation. If we inject scripts lately, we should either tell the scripts about the special `@run-at` and force them to deal with it or break many of them. On the other hand, if the extension is disabled and enabled again, it is hard to know if a tab has been injected with some scripts before.
AFAIK, a saved session is just a group of URLs, which will be loaded on browser start. So reloading them again when the extension is ready (maybe after several hundreds of milliseconds) should not be a bad option.

**Comment by filbo** [comment] 2018-05-25 03:14
If you can contrive to reliably do that only at browser startup, _not_ when VM is re-activated during a long browser session, that might be alright.

**Comment by gera2ld** [comment] 2018-05-25 07:42
That's why I prefer reloading manually, or just an option to reload existing tabs.

**Comment by filbo** [comment] 2018-05-25 08:29
Reloading manually means the user of the userscript thinks it's broken.  End users are not going to understand this stuff, they just understand 'the thing I'm using doesn't work consistently'.

I am going to assume that you _can_ detect at VM-startup time, how long the browser as a whole has been running.  If that is less than some threshold, let's say 2000ms, then as you scan the tabs deciding which need scripts injected, each tab into which you are going to inject should be reloaded.

Yes, this should be an optional behavior; with default setting of YES, DO THIS.  Advanced users can turn it off if they need to.

OR, come up with a better way to ensure that tabs actually come up with the intended behavior at browser-start time.

And fix the same bug wrt VM's own 'dashboard' UI page.

**Comment by filbo** [comment] 2018-11-08 02:54
This **is** still an outstanding issue for me (on Opera); and I've just had a user report of similar stuff on Firefox.  The FF case didn't have anything to do with VM, in fact it was about FF extension 'New Tab Tools', but the user experience of _extension doesn't start correctly in a tab which was part of the FF load-time tabset_ is identical; it goes to show that the root cause of the issue still exists and unfortunately needs to be dealt with by extension authors.

And, I think it's perhaps not of great significance to an individual extension author.  But the problem is force-multiplied in the case of an extension which happens to be a userscript manager: now the problem is being dealt out to N dependent userscripts, where N could be large or userscripts could be important.

It still happens to me constantly with (1) FB tabs which were loaded as part of startup tabset (Social Fixer userscript does not start); (2) if I had the VM dashboard open in a tab, it does not initialize until I hit _ctrl-R_.

Please fix?

**Comment by filbo** [comment] 2018-12-29 11:21
Updating this so I can mention it to Opera; current as of 2018-12-29

1. Install opera-developer (I got 59.0.3173.0):

https://www.opera.com/computer/beta, Opera developer [Download now]

2. Run Opera with a scratch profile directory:

$ opera-developer --user-data-dir=/tmp/startup-bug

[or Windows equivalent, whatever that would be]

3. Install Violentmonkey (I got 2.10.1):

https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag

Opera prompts: 'Do you want to install extensions from the Chrome Web Store? By installing Install Chrome Extensions you accept our Permissions.  [Install extension]'; click that button (this installs the Opera 'Install Chrome Extensions' extension).

Chrome 'store' Violentmonkey page reloads; click 'Add to Opera'.

'Install Chrome Extensions' subwindow pops up; click 'OK'.

opera://extensions opens, showing Violentmonkey present but not installed; click 'Install', then 'Yes, install'.

4. Install test script:

Violentmonkey icon (right of address bar) -> Open Dashboard

'+' -> New

Click within the new script; select all (ctrl-A or equivalent); erase (backspace)

Copy and paste in (from '// ==Userscript' through '880088";'):

========================================

// ==UserScript==
// @name Testing VM startup
// @namespace https://github.com/violentmonkey/violentmonkey/issues/73
// @include /^https?://*/
// @run-at document-start
// @Version 2018-12-29
// ==/UserScript==
document.body.style.background = "#880088";

========================================

[Save & Close]

5. Create test tabs:

Open https://github.com/does-not-exist -- should produce 404 page, background of lower part is purple

Right-click the github 'Page not found' tab in the tab bar > Close other tabs (leaving only the purple github tab)

Right-click on tab, 'Duplicate tab' -- 2nd tab, background is purple

Clone a total of 8 tabs this way

Open Violentmonkey 'dashboard' as 9th tab (session now consists of 8 purplized github.com 404 tabs + 1 VM dashboard)

6. Close Opera

7. Reopen Opera:

$ opera-developer --user-data-dir=/tmp/startup-bug

8. Look at all 9 tabs -- are the 1st 8 all purplized?  Is VM dashboard running in the 9th?  (Note: ctrl-1 through ctrl-9 visit 9 tabs)

9. Goto 6, repeat until problem observed.  For me, the first reopen after installation has all tabs in good working order, subsequent ones have at least one tab in bad order (the first tab which was visible when the session was reloaded).  'In bad order' means: for the 404 tabs, background is not purple; for the VM dashboard tab, dashboard does not start.

10. The setting opera://settings/?search=delay+loading+of+background+tabs modifies the misbehavior.  With it enabled (default), only the first-visible tab is in bad order; with it disabled, all tabs are in bad order.  The problem is clearly timing related and individual run results may vary, but these are the most frequent results.

Note: cannot reproduce this behavior with Opera 59.0.3173.0 + Tampermonkey 4.7.54.  But I *have* seen it with other extensions, so either there is a common mistake which extensions can make (including VM), or TM is intentionally working around some common browser timing bug / misbehavior.  Have also seen the same misbehavior on other browsers including Chrome & Firefox, but have not carefully worked up a repro document like this.

**Comment by tophf** [comment] 2019-10-14 19:37
This should be fixed in the upcoming version of VM thanks to 33108ed9.

**Comment by filbo** [comment] 2019-10-15 21:42
Thanks!

You wrote:

  // The active web page tab and its content scripts load before the background script
  // when Chrome starts with a URL (via command line or when configured to restore the session).

I've seen this affect other extensions; I think it is fundamentally a startup sequencing bug in the browsers.  Fixing it in VM is good.  Would you mind also raising it as a bug to Google & Mozilla?  I don't know how to explain the problem well enough to write a good report.

**Comment by tophf** [comment] 2019-10-16 04:08
https://crbug.com/314686

**Comment by filbo** [comment] 2019-10-16 04:37
Great.  6yo bug, bounced around various 'owners' who never do anything, including letting it sit in 'triage' for 2y.

**Closed** 2019-11-17 15:31 UTC
