### ISSUE TITLE
viewtube user script not working with violent monkey 2.8.8 and firefox nighlty v57 android(version 2.6.4 is ok)

### ISSUE THREAD

**Issue by ale82to** [violentmonkey/violentmonkey#210] opened 2017-09-13 23:33 UTC
### How to reproduce it?
1.install latest firefox nighlty v57 from playstore and latest tampermonkey extension 2.8.8
2 install view tube userscript https://greasyfork.org/en/scripts/2984-viewtube

### What is the expected result?
on youtube mobile webpages( https://m.youtube.com/watch?v=Hu80uDzh8RY for example) viewtube user script should work  loading custom player, but with tampermonkey 2.8.8 script wont work,with 2.6.4 version of violent monkey everything s fine instead(same firefox nighlty v.57 version)

### What is the actual result?
viewtube userscript wont load custom player(asking desktop site sometimes fixes the issue)

### Environment
- Browser:firefox nighlty v57
- Browser version:57
- Violentmonkey version:2.8.8
- OS: android 6.01

**Comment by Mattwmaster58** [comment] 2017-10-08 02:02
>  tampermonkey 2.8.8 script wont work,with 2.6.4 version of violent monkey everything s fine instead

Can you clarify?

**Comment by ale82to** [comment] 2017-10-13 16:10
I m super dissapori red i wasted my time trying to be as detailed as possible to reporting the bug and it hasn't  be fixed yet
is that so hard to reproduce it  ?
just install viewtube userscript and volentent monkey version 2.6.4 on Firefox for Android version 58 nightly everything works just as expected install same userscript and update to any newer version of violent monkey even the latest and user script won't work
come on

**Comment by gera2ld** [comment] 2017-10-14 04:22
I have wasted a lot of time debugging this issue, and finally figured out the problem.

### What is the real problem?
The script modifies the player, so does Youtube. Ideally, the script should modify the player after Youtube modifies it, then everything works well. The issue is, sometimes the script modifies the script even before Youtube, which breaks it.
The script does not specify a `@run-at` key, which is default by `document-end`, meaning that as soon as the initial HTML document is ready, the script may be executed. At `document-end`, the player is already initiated by Youtube on Desktop version but not on Mobile version. That's why the script works for Desktop Youtube but breaks on Mobile version.

IMO, this is a issue to the script and should be fixed by the script author.

BTW, I tested it on v2.6.4 and it does not work either.

### Solution
A workaround is to modify the script or custom `@run-at` to `document-idle`.
Anyway I will delay the script injection from *at* to *after* `DOMContentLoaded` to avoid such problems.

**Closed by gera2ld** 2017-10-14 04:22 UTC

**Comment by ale82to** [comment] 2017-10-14 22:30
thanks for looking into the issue! anyway with today firefox nighlty v58 even setting at document idle wont solve the issue for me

**Comment by ale82to** [comment] 2017-10-14 23:20
so sad(after so many wasted time) to discover everthing is working fine on tampemonkay so i m back on it
