### ISSUE TITLE
2.9.8 stopped working

### ISSUE THREAD

**Issue by pikopikopikopiko** [violentmonkey/violentmonkey#466] opened 2018-10-24 19:42 UTC
2.9.8 stopped working
hangs on loading scripts

**Comment by edwcb** [comment] 2018-10-24 19:50
Lost all scripts after update to 2.9.8. 
Even restore from backup it still not working,  just loading..

**Comment by Merseybuoy** [comment] 2018-10-24 19:52
As above. Reverted to 2.9.7.

**Comment by nuiva** [comment] 2018-10-24 19:53
To elaborate, dashboard installed scripts tab is forever "Loading ...". The toolbar menu shows "Scripts disabled", and clicking it does not enable scripts, except visually on some pages. No scripts visible in data export in dashboard settings tab.

**Comment by kkapsner** [comment] 2018-10-24 19:58
Same for me. It might be related to the warning in the debug page:
![image](https://user-images.githubusercontent.com/1105157/47457606-d669d280-d7d7-11e8-9527-9e5e956b7684.png)

PS: running Firefox 63.0 64-Bit on Linux

**Comment by Delerium69** [comment] 2018-10-24 20:03
Same here firefox 63.0 64bit on windows. Import of scripts doesnt import them back - addon wont switch on. :(

**Comment by Delerium69** [comment] 2018-10-24 20:03
> 
> 
> As above. Reverted to 2.9.7.

how did you revert back to previous version?

**Comment by kkapsner** [comment] 2018-10-24 20:07
https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/

**Comment by mooms06** [comment] 2018-10-24 20:09
I confirm, same issue here, rolling back to 2.9.7 fixed the issue.

**Comment by irgendwie** [comment] 2018-10-24 20:09
Reverted back to 2.9.7 -> lost all scripts - only for me? :-/

**Comment by kkapsner** [comment] 2018-10-24 20:12
Scripts are still there after rollback.

**Comment by perdolka** [comment] 2018-10-24 20:14
same

**Comment by StanGets** [comment] 2018-10-24 20:57
Same here with ViolentMonkey 2.9.8 / Firefox 63.0 (x64) / Windows 7 (x64)
When I opened VM's Dashboard the screen displayed "Loading..." and never loaded.
I reverted to 2.9.7 and all is ok

**Comment by iou1name** [comment] 2018-10-24 21:12
Same story. I'm on FF 64.03b

**Comment by kkapsner** [comment] 2018-10-24 21:17
Also broken on nightly 65.0a1 (2018-10-24) - after commit e6b5cd672878918103d78bebc0aaa5cd27d1bf19 it still works. So I assume it's the huge a83334c018dd6d0c4924537fde8bea02129aa0f9 which breaks...

**Comment by StanGets** [comment] 2018-10-24 21:18
@Delerium69 :

> how did you revert back to previous version?

Simply be installing VM 2.9.7 from https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/versions/

**Comment by Delerium69** [comment] 2018-10-24 21:18
Rollback worked (lost scripts tho - thank god for backups)

**Comment by kkapsner** [comment] 2018-10-24 21:45
Yes - confirmed: it's a83334c
Problem seems to be that the promise from `browser.runtime.sendMessage()` does not have a proper value.

**Comment by kkapsner** [comment] 2018-10-24 22:05
One of the used libraries replaces the native Promise... and as stated in the code:`// If res is not instance of native Promise, browser APIs will not wait for it.` (https://github.com/violentmonkey/violentmonkey/blob/master/src/background/index.js#L224)

So it's not the content of the commit but the change/update of the libraries itself.

**Comment by streamingfeedback** [comment] 2018-10-24 22:06
Installing 2.9.7 works, but when Firefox checks for updates it goes right back to 2.9.8. Is there an estimated time for when the fix will be released?

**Comment by Vangelis66** [comment] 2018-10-24 22:07
Add my voice to those above... 😭 I am running **Serpent 52.9.0** (a fork of **Basilisk 52** capable of running on XP/Vista) 32-bit, once I manually updated to **2.9.8**, I was faced with the predicament detailed in previous comments...

**Comment by po5** [comment] 2018-10-24 22:09
Same here.

**Comment by XspeedPL** [comment] 2018-10-24 22:10
Please stop writing "it doesn't work", it's been pretty much confirmed and kkapsner has even found the reason

**Comment by kkapsner** [comment] 2018-10-24 22:10
@streamingfeedback you can disable updates for an addon: 
![image](https://user-images.githubusercontent.com/1105157/47464719-6d3f8a80-d7ea-11e8-847c-76c1e28a10bb.png)

**Comment by kkapsner** [comment] 2018-10-24 22:44
No luck in finding the library that causes the problem. (My guess is core-js and it's es6.promise.js)
I'm tired and will go to bed.

**Comment by kkapsner** [comment] 2018-10-24 22:58
Couldn't help... it's in core-js/modules/es6.promise.js the `USE_NATIVE` which should be true but isn't.
@gera2ld I fixed it by altering the compiled common.js and browser.js:
![image](https://user-images.githubusercontent.com/1105157/47466222-9105cf00-d7f0-11e8-8e2a-d4b393d81a4a.png)

**Comment by kkapsner** [comment] 2018-10-24 22:59
The problem is that Firefox does not support https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent

**Comment by kkapsner** [comment] 2018-10-24 23:07
Now let's see what core-js and gera2ld do with that information. In the meantime the only way for Firefox users is to go back to 2.9.7

**Comment by Azraelle** [comment] 2018-10-25 00:11
>    Firefox doesn't yet send the unhandledrejection or understand rejectionhandled events. Completing the implementation will be addressed in bug 1362272.
  

>  Disabled This feature is behind the dom.promise_rejection_events.enabled preference (needs to be set to true). To change preferences in Firefox, visit about:config

it works.

**Comment by Vangelis66** [comment] 2018-10-25 00:45
>> Disabled This feature is behind the dom.promise_rejection_events.enabled preference 
>> (needs to be set to true). To change preferences in Firefox, visit about:config
> 
> it works.

Unfortunately, this is _no consolation_ for us on forks of **FirefoxESR 52**; the pref `dom.promise_rejection_events.enabled` was implemented by [Bug 1338059](https://bugzilla.mozilla.org/show_bug.cgi?id=1338059) in mercurial changeset [61af8ff774fe](https://hg.mozilla.org/mozilla-central/rev/61af8ff774fe), i.e. landed in the **55.0a1** Nightly cycle... On AMO, Violentmonkey 2.9.0+ is marked as installable in/compatible with _**Firefox 42.0 and later**_ ... 

I, most certainly, would like to keep on using VM in my Serpent 52.9.0 browser; let us hope the "fixed" new release will allow me to do so... 😕

**Comment by gabri25ele** [comment] 2018-10-25 06:28
it's incredible/terrible!!!!!!
but authors, try them before issuing an update!
crazy stuff

**Comment by sleeyax** [comment] 2018-10-25 06:56
Same here, suddenly stopped working. 
It throws this message in the developer console:
```
Unhandled promise rejection TypeError: "promise.then is not a function"
```

**Closed** 2018-10-25 07:04 UTC

**Comment by Vangelis66** [comment] 2018-10-25 14:43
@kkapsner wrote: 

> Now let's see what **core-js** (snip) do with that information.

... Absolutely nothing (👎) , that's what that dev did with it... 

@gabri25ele wrote: 

> but authors, try them before issuing an update!

... Both the above come as a direct result of _Google Chrome becoming the dominant browser_ in the market, enabling Google to dictate what the standards (or non-standards 😉 ) should be for the current web! Web page designers and browser extension authors primarily target **Chromium** as the reference browser, leaving other non-webkit vendors on a constant catch-up struggle...

To be fair to @gera2ld, this repo only hosts releases for Chromium type browsers (.**crx** files, and up to version **2.9.5**), so my gut feeling is he only tested the 2.9.8 release on Chrome and assumed it'd be also OK for other supported browsers... We'll forgive and forget this slightest slip, given the excellent extension he provides to us all 😄 
Many thanks indeed for the update to 2.9.9, which functions properly 
on **Basilisk** browser (and its forks) 🥇 :heart:

**Comment by chocolateboy** [comment] 2019-08-13 14:33
Seeing this error again in 2.11.12:

> Unhandled promise rejection TypeError: promise.then is not a function
