### ISSUE TITLE
should I stay on version 2.8.13?

### ISSUE THREAD

**Issue by rezad1393** [violentmonkey/violentmonkey#285] opened 2017-11-16 16:32 UTC
- Browser:firefox
- Browser version: 57
- Violentmonkey version: 2.8.13
- OS:linux

can the blob bug be fixed for newer version? this causes violentmonkey not to work with csp enables websites. 
 [ use src with Blob for injection ](https://github.com/violentmonkey/violentmonkey/commit/796cddd9f19b1b627a7f4e2071e96d766d76eef4)
the error is explained on another issue as firefox bug of stopping blob script on csp websites in firefox 57 and has a workaround for firefox 58.
can violentmonkey be configured so that on firefox it uses the old method at least until firefox 58 is released as stable?

**Comment by rezad1393** [comment] 2017-11-16 16:57
if this is not possible then shouldn't the version 2.8.14 should be noted as incompatible with firefox version 57?

**Comment by gera2ld** [comment] 2017-11-17 02:22
It makes no difference on CSP limited websites in Firefox 57, because both ways are broken.
For sites without CSP limitations, it may break sometimes. Closing as duplicate of #277 .

**Closed by gera2ld** 2017-11-17 02:22 UTC

**Comment by rezad1393** [comment] 2017-11-18 13:05
the 2.8.13 version works fine for me.
then why you say both ways are broken?
I can use 2.8.13 on csp enabled website and it works.
I dont understand your answer.

**Comment by rezad1393** [comment] 2017-11-18 13:52
the 2.8.13 version works fine for me.
then why you say both ways are broken?
I can use 2.8.13 on csp enabled website and it works.
I dont understand your answer.

**Comment by gera2ld** [comment] 2017-11-20 02:14
Because Firefox 57 does not support script injection into CSP limited pages, unless you have changed it in `about:config`.
If this is the case, can you tell how the scripts are broken and what is shown in console? Please fill the issue template, otherwise I cannot reproduce your problem and this issue will be regarded as `invalid`.

**Comment by rezad1393** [comment] 2017-11-20 09:44
maybe I was not clear.
I have firefox 57 and violentmonkey 2.8.13 installed.
all of my scripts work as far as I know.
but if I update violentmonkey to 2.8.14 then scripts wont run on csp websites.

again: they work on csp site with violentmonkey 2.8.13 installed and dont work with 2.8.14 installed.

hope I was clear enough.

**Comment by rezad1393** [comment] 2017-11-21 18:30
2.8.19 is also not working.
you confused the order.
blobs are not run at csp pages. not the other way around

**Comment by Remu-rin** [comment] 2017-11-22 14:52
> If this is the case, can you tell how the scripts are broken and what is shown in console?

Fixed for me in 2.8.20 (Firefox 57), but to clear things up: script was https://github.com/SthephanShinkufag/Dollchan-Extension-Tools (ESNext version), page was https://boards.4chan.org/g/. With 2.8.13 and 2.8.20 script works (icon in the right bottom corner) and console shows nothing. In versions between them script isn't worked and console showed:
> Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://boards.4chan.org/3a4f5542-edea-4897-b790-408da1ff7a5b (“default-src https://boards.4chan.org * data: 'unsafe-inline' 'unsafe-eval'”).

**Comment by rezad1393** [comment] 2017-11-22 19:17
yes 
the 2.8.19 didnt work. but 2.8.20 now works for my scripts.

**Comment by rezad1393** [comment] 2017-12-01 12:47
and now 2.8.21 is not working for any scripts.
can the author tell me if he even test the releases uploaded to AMO with any scripts?
