### ISSUE TITLE
Select link script don't work correctly

### ISSUE THREAD

**Issue by birykvlad** [violentmonkey/violentmonkey#232] opened 2017-10-05 10:06 UTC
I am use this script for select link (from any place). In Greasemonkey his work fine. But in Violentmonkey script don't work. Example: https://news.yandex.ru .

[vm.zip](https://github.com/violentmonkey/violentmonkey/files/1358870/vm.zip)
================
- Browser: Mozilla Firefox
- Browser version: 56.0
- Violentmonkey version: 2.8.10f
- OS: Windows 10 x64

**Comment by gera2ld** [comment] 2017-10-06 05:43
What does this script do? Please fill the issue template.

I guess this issue might be related to CSP, maybe duplicate of #173 .

**Comment by birykvlad** [comment] 2017-10-06 07:25
This script selects links as plain text from anywhere, for example, from the middle of a word.

**Comment by gera2ld** [comment] 2017-10-06 08:28
For me it works on Firefox and sites without CSP limitations. And it won't work on Chrome.
In your case it is because <https://news.yandex.ru> has a strict CSP header, which is a known issue. Closing this on duplicate of #173 .

PS: Please provide a minimal reproduction as described in the issue template. I don't want to take time to find out what a script does every time.

**Closed by gera2ld** 2017-10-06 08:28 UTC
