### ISSUE TITLE
Add global keyboard shortcut for updating scripts

### ISSUE THREAD

**Issue by dutzi** [violentmonkey/violentmonkey#988] opened 2020-05-06 09:08 UTC
It would be useful if, in addition to existing shortcuts (Activate the extension, Open dashboard, etc...) we could set a shortcut for "Check for script updates".

**Comment by tophf** [comment] 2020-05-06 09:11
Looks like a duplicate of #973.

**Closed by tophf** 2020-05-06 09:11 UTC
