### ISSUE TITLE
Nextcloud Support

### ISSUE THREAD

**Issue by AdamBryantSkybox** [violentmonkey/violentmonkey#224] opened 2017-09-30 17:21 UTC
In this case, would it be possible to just have a generic "folder sync" support feature?
Would love to have a single sync method, though for now I am using Dropbox for it. I host my own nextcloud server.

**Comment by gera2ld** [comment] 2017-10-02 08:12
maybe duplicate of #100

**Comment by AdamBryantSkybox** [comment] 2017-10-02 15:01
Yes, Nextcloud uses WebDav.

**Comment by NudeSpoons** [comment] 2018-05-17 09:10
@gera2ld As @AdamBryantSkybox agrees that this is a duplicate of #100, I suggest that this issue be likewise given the `enhancement` label, plus a new `duplicate` label, and then closed.  I presume that only you can do so.

**Comment by gera2ld** [comment] 2018-05-24 06:10
close as duplicate of #100

**Closed by gera2ld** 2018-05-24 06:10 UTC
