### ISSUE TITLE
2.12.2 break the sites v2

### ISSUE THREAD

**Issue by wvxwxvw** [violentmonkey/violentmonkey#735] opened 2019-11-26 11:58 UTC
GitHub - Unable to edit your posts in Issues.
Yandex Disk - Unable to go to folder / archive

Reproduced. Breaks the specified sites with the mode of injection "auto" and "page". Regardless of the activated scripts, you can do without scripts.

**Comment by wvxwxvw** [comment] 2019-11-26 12:03
I'm not a scriptwriter or a programmer. I found out by multiple tests. Understand further on your own.

**Comment by gera2ld** [comment] 2019-11-26 12:05
Closing as duplicate of #733

**Closed by gera2ld** 2019-11-26 12:05 UTC
