### ISSUE TITLE
"We may use Google Analytics to collect your browser information"

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [violentmonkey/violentmonkey#602] opened 2019-09-03 21:07 UTC
### What is the problem?

Directly from Violentmonkey's privacy policy: "We may use Google Analytics to collect your browser information anonymously to help improve compatibility."

Why..? This is unneeded. It would be a good decision to remove this, or make it an opt-in only feature, disabled by default. This is a privacy concern. I've come across many users switching off violentmonkey simply due to this. It doesn't matter if it's anonymously collected, this is what people don't want. They don't want their data collected like this. Please, I highly encourage you to remove this.

Screenshot: https://b.catgirlsare.sexy/cTV7.png

### How to reproduce it?
1. View Privacy Policy

**Comment by gera2ld** [comment] 2019-09-04 04:46
Thanks for the kind suggestion.

To make it clear, I plan to collect the browser type / version and system type / version so that I can decide which browsers to support when considering new JavaScript features.

I'm wondering if my words are improper or people just don't want anything to be collected? If the latter is true, I think I can remove that plan and just drop support for old browsers in the future.

**Comment by Z3ROGRAV1TYx** [comment] 2019-09-04 13:28
>To make it clear, I plan to collect the browser type / version and system type / version so that I can decide which browsers to support when considering new JavaScript features.

Yes but I agree with them, I understand your reasoning but a lot of people who are privacy conscious simply want to minimize/deny data collection, and I think it's a good idea to either have it disabled by default and allow people to opt-in or the other way around, or even better just completely disable it. I genuinely think this would be a good descision.

**Comment by maple3142** [comment] 2019-09-04 13:50
@Z3ROGRAV1TYx The problem is if it is **opt-in**, almost no one will turn it on. I agree that there should be a button to disable analytics, but whether it should be on or off by default is debatable.
Currently, there is no such button in Violentmonkey settings to turn off analytics , and it should be one there.

**Comment by Z3ROGRAV1TYx** [comment] 2019-09-04 14:05
> 
> 
> @Z3ROGRAV1TYx The problem is if it is **opt-in**, almost no one will turn it on. I agree that there should be a button to disable analytics, but whether it should be on or off by default is debatable.
> Currently, there is no such button in Violentmonkey settings to turn off analytics , and it should be one there.

> or the other way around
as I stated. But yes the option should be there regardless imo.

**Comment by Z3ROGRAV1TYx** [comment] 2019-09-19 21:42
@gera2ld Do you know yet if you are planning on making this an opt-out feature?

**Comment by gera2ld** [comment] 2019-09-25 04:33
@Z3ROGRAV1TYx I will drop the plan to collect browser info and only support newer browsers in the future.

> I think it's a good idea to either have it disabled by default and allow people to opt-in or the other way around

I don't want to spend too much time in such a feature so just forget it. 😄

**Comment by gera2ld** [comment] 2019-11-06 16:04
Closing since the privacy policy is updated.

**Closed** 2019-11-06 16:05 UTC

**Comment by apiraino** [comment] 2019-11-06 22:15
I find that a "thank you" is due to @gera2ld for accomodating this request. 

thanks!

**Comment by Z3ROGRAV1TYx** [comment] 2019-11-06 23:13
Thank you!

**Comment by pikim** [comment] 2020-03-02 16:54
Why is there still a passage that states that you may use Google Analytics?

**Comment by tophf** [comment] 2020-03-02 16:57
Violentmonkey doesn't use GA so apparently @gera2ld simply missed this paragraph when fixing https://github.com/violentmonkey/violentmonkey.github.io/commit/7964469da138b2c5db43d01d8f03820ac7cc5813.

**Comment by FlowerForWar** [comment] 2022-05-26 02:50
For whatever reason, I have always preferred [violentmonkey](https://github.com/violentmonkey/violentmonkey), glad this issue is no more.

**Comment by vut007847-crypto** [comment] 2025-12-06 11:37
// ==UserScript==
// @name         ScriptGTD-Quest
// @namespace    http://tampermonke
// @version      2025-10-03
// @description  Script sá»­ dá»¥ng Ä‘á»ƒ hack NhiemVuHangNgay
// @author       Snow
// @match        https://gtd-cdn.gamehollywood.com/GTD_service/index_gh.html*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=gamehollywood.com
// @grant        none
// ==/UserScript==

(function () {

  'use strict';
// 1. Setup nhiá»‡m vá»¥ (QUEST_WEEKLY)
// ===============================
setInterval(() => {
    if (QUEST_WEEKLY[1].arrive === 0 || QUEST_WEEKLY[1].arrive === 2) {
    QUEST_WEEKLY[1].status= 30;
    QUEST_WEEKLY[2].status= 50;
    QUEST_WEEKLY[3].status=500;
    QUEST_WEEKLY[4].status= 30;
    QUEST_WEEKLY[5].status= 5;
    QUEST_WEEKLY[6].status= 30;
    QUEST_WEEKLY[7].status= 1;
    QUEST_WEEKLY[8].status= 50;
    QUEST_WEEKLY[9].status= 6;
    QUEST_WEEKLY[10].status= 100;
        console.log("Snow Ä‘Ă£ chuáº©n bá»‹ phĂ n thÆ°á»Ÿng nhiá»‡m vá»¥");
    }
}, 2000); // kiá»ƒm tra má»—i 2 giĂ¢y trĂ¡nh deley
// ===============================
// 2. Hack nhiá»‡m vá»¥
// ===============================
setInterval(() => {
    if (QUEST_WEEKLY[1].arrive === 0 || QUEST_WEEKLY[1].arrive === 2) {
        for (let i = 1; i < 11; i++) {
            QUEST_WEEKLY[i].arrive = 1;
            }
            console.log("Snow Ä‘Ă£ cho báº¡n pháº§n thÆ°á»Ÿng");
    }
}, 2000); // kiá»ƒm tra má»—i 2 giĂ¢y trĂ¡nh deley

})();// ==UserScript==
// @name        New script
// @namespace   Violentmonkey Scripts
// @match       *://example.org/*
// @grant       none
// @version     1.0
// @author      -
// @description 12:06:58 7/9/2025
// ==/UserScript==

**Comment by vut007847-crypto** [comment] 2025-12-06 11:38
// ==UserScript==
// @name         ScriptGTD-Quest
// @namespace    http://tampermonke
// @version      2025-10-03
// @description  Script sá»­ dá»¥ng Ä‘á»ƒ hack NhiemVuHangNgay
// @author       Snow
// @match        https://gtd-cdn.gamehollywood.com/GTD_service/index_gh.html*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=gamehollywood.com
// @grant        none
// ==/UserScript==

(function () {

  'use strict';
// 1. Setup nhiá»‡m vá»¥ (QUEST_WEEKLY)
// ===============================
setInterval(() => {
    if (QUEST_WEEKLY[1].arrive === 0 || QUEST_WEEKLY[1].arrive === 2) {
    QUEST_WEEKLY[1].status= 30;
    QUEST_WEEKLY[2].status= 50;
    QUEST_WEEKLY[3].status=500;
    QUEST_WEEKLY[4].status= 30;
    QUEST_WEEKLY[5].status= 5;
    QUEST_WEEKLY[6].status= 30;
    QUEST_WEEKLY[7].status= 1;
    QUEST_WEEKLY[8].status= 50;
    QUEST_WEEKLY[9].status= 6;
    QUEST_WEEKLY[10].status= 100;
        console.log("Snow Ä‘Ă£ chuáº©n bá»‹ phĂ n thÆ°á»Ÿng nhiá»‡m vá»¥");
    }
}, 2000); // kiá»ƒm tra má»—i 2 giĂ¢y trĂ¡nh deley
// ===============================
// 2. Hack nhiá»‡m vá»¥
// ===============================
setInterval(() => {
    if (QUEST_WEEKLY[1].arrive === 0 || QUEST_WEEKLY[1].arrive === 2) {
        for (let i = 1; i < 11; i++) {
            QUEST_WEEKLY[i].arrive = 1;
            }
            console.log("Snow Ä‘Ă£ cho báº¡n pháº§n thÆ°á»Ÿng");
    }
}, 2000); // kiá»ƒm tra má»—i 2 giĂ¢y trĂ¡nh deley

})();// ==UserScript==
// @name        New script
// @namespace   Violentmonkey Scripts
// @match       *://example.org/*
// @grant       none
// @version     1.0
// @author      -
// @description 12:06:58 7/9/2025
// ==/UserScript==
